import type { Model } from './types';

/**
 * 模型目录（占位数据）。官方价单位：美元 / 百万 Token；生图按张为美元 / 张。
 * 本站价格 = 官方价 × 所选版本的分组倍率（见 editions.ts），这里只放官方价。
 * 型号与官方价参考 onehop.ai 2026-10-03 公开价目推算，替换时只改这里。
 */
export const MODELS: readonly Model[] = [
  // ---------- OpenAI 文本 ----------
  {
    id: 'gpt-6-astra',
    name: 'GPT-6 Astra',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    released: '2026-09-18',
    description: {
      zh: 'OpenAI 新一代旗舰，推理、编码与 Agent 任务的最强档。',
      en: "OpenAI's new flagship, the strongest tier for reasoning, coding and agentic work.",
    },
    official: { input: 10, output: 50, cacheRead: 1 },
    longContext: { threshold: 272_000, input: 20, output: 75 },
    image: null,
  },
  {
    id: 'gpt-6-sol',
    name: 'GPT-6 Sol',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    released: '2026-09-18',
    description: {
      zh: 'GPT-6 均衡档，面向交互式编码与 Agent，可靠性接近 Astra。',
      en: 'The balanced GPT-6 tier for interactive coding and agents, close to Astra in reliability.',
    },
    official: { input: 2, output: 10, cacheRead: 0.2 },
    longContext: { threshold: 272_000, input: 4, output: 15 },
    image: null,
  },
  {
    id: 'gpt-6-luna',
    name: 'GPT-6 Luna',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    released: '2026-09-25',
    description: {
      zh: 'GPT-6 家族最快、最便宜的一档，适合目标明确的高并发任务。',
      en: 'The fastest, most affordable GPT-6 tier for well-scoped, high-volume tasks.',
    },
    official: { input: 0.1, output: 0.5, cacheRead: 0.01 },
    longContext: { threshold: 272_000, input: 0.2, output: 0.75 },
    image: null,
  },
  {
    id: 'gpt-5.6-sol',
    name: 'GPT-5.6 Sol',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    released: '2026-08-20',
    description: {
      zh: 'GPT-5.6 旗舰，面向最难的推理、编码与 Agent 任务。',
      en: 'GPT-5.6 flagship for the hardest reasoning, coding and agent tasks.',
    },
    official: { input: 4, output: 20, cacheRead: 0.4 },
    longContext: { threshold: 272_000, input: 8, output: 30 },
    image: null,
  },
  {
    id: 'gpt-5.6-terra',
    name: 'GPT-5.6 Terra',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    released: '2026-08-20',
    description: {
      zh: 'GPT-5.6 均衡款，兼顾生产级能力与成本。',
      en: 'Balanced GPT-5.6 model that weighs production-grade capability against cost.',
    },
    official: { input: 2, output: 12, cacheRead: 0.2 },
    longContext: { threshold: 272_000, input: 4, output: 18 },
    image: null,
  },
  {
    id: 'gpt-5.6-luna',
    name: 'GPT-5.6 Luna',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    released: '2026-08-20',
    description: {
      zh: 'GPT-5.6 高效款，适合高并发与延迟敏感场景。',
      en: 'Efficient GPT-5.6 model for high-concurrency, latency-sensitive workloads.',
    },
    official: { input: 0.2, output: 1.2, cacheRead: 0.02 },
    longContext: { threshold: 272_000, input: 0.4, output: 1.8 },
    image: null,
  },
  {
    id: 'gpt-5.5',
    name: 'GPT-5.5',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_000_000,
    released: '2026-06-10',
    description: {
      zh: '上一代旗舰，百万上下文，推理与 Agent 编码依然顶级。',
      en: 'Previous-generation flagship with a 1M context, still top-tier at reasoning and agentic coding.',
    },
    official: { input: 5, output: 30, cacheRead: 0.5 },
    longContext: { threshold: 272_000, input: 10, output: 45 },
    image: null,
  },

  // ---------- Anthropic ----------
  {
    id: 'claude-fable-5-1',
    name: 'Claude Fable 5.1',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 1_000_000,
    released: '2026-09-10',
    description: {
      zh: 'Anthropic 能力最强的模型，适合最复杂的长程推理与研究任务。',
      en: "Anthropic's most capable model for the most complex long-horizon reasoning and research.",
    },
    official: { input: 10, output: 50, cacheRead: 1 },
    longContext: null,
    image: null,
  },
  {
    id: 'claude-opus-5',
    name: 'Claude Opus 5',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 1_000_000,
    released: '2026-08-06',
    description: {
      zh: 'Opus 旗舰，Agent 编码与长程任务表现突出。',
      en: 'Flagship Opus with standout agentic coding and long-running task performance.',
    },
    official: { input: 5, output: 25, cacheRead: 0.5 },
    longContext: null,
    image: null,
  },
  {
    id: 'claude-sonnet-5-5',
    name: 'Claude Sonnet 5.5',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 1_000_000,
    released: '2026-09-30',
    description: {
      zh: '最快的 Sonnet，编码能力接近 Opus，价格仍是 Sonnet。',
      en: 'The fastest Sonnet, with coding close to Opus at Sonnet pricing.',
    },
    official: { input: 2, output: 10, cacheRead: 0.2 },
    longContext: null,
    image: null,
  },
  {
    id: 'claude-sonnet-5',
    name: 'Claude Sonnet 5',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 1_000_000,
    released: '2026-06-25',
    description: {
      zh: 'Agent 能力最强的 Sonnet，接近 Opus 水平。',
      en: 'The most agentic Sonnet, approaching Opus-level capability.',
    },
    official: { input: 3, output: 15, cacheRead: 0.3 },
    longContext: null,
    image: null,
  },
  {
    id: 'claude-opus-4-8',
    name: 'Claude Opus 4.8',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 1_000_000,
    released: '2026-04-16',
    description: {
      zh: '上一代 Opus，推理与编码稳定可靠。',
      en: 'Previous-generation Opus, steady at reasoning and coding.',
    },
    official: { input: 5, output: 25, cacheRead: 0.5 },
    longContext: null,
    image: null,
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 200_000,
    released: '2025-10-15',
    description: {
      zh: '最快、最经济的 Claude，适合分类、抽取等轻量任务。',
      en: 'The fastest, most economical Claude for classification, extraction and other light tasks.',
    },
    official: { input: 1, output: 5, cacheRead: 0.1 },
    longContext: null,
    image: null,
  },

  // ---------- Google 文本 ----------
  {
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    provider: 'google',
    type: 'text',
    protocols: ['gemini', 'openai-chat'],
    contextTokens: 1_000_000,
    released: '2026-08-27',
    description: {
      zh: '接近旗舰的智能，保持 Flash 的速度与成本。',
      en: 'Near-flagship intelligence at Flash speed and cost.',
    },
    official: { input: 1.5, output: 9, cacheRead: 0.375 },
    longContext: null,
    image: null,
  },
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro',
    provider: 'google',
    type: 'text',
    protocols: ['gemini', 'openai-chat'],
    contextTokens: 1_000_000,
    released: '2026-05-20',
    description: {
      zh: 'Google 旗舰，数学推理与代码能力顶级。',
      en: "Google's flagship, top-tier at mathematical reasoning and code.",
    },
    official: { input: 2, output: 12, cacheRead: 0.5 },
    longContext: { threshold: 200_000, input: 4, output: 18 },
    image: null,
  },
  {
    id: 'gemini-3.1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    provider: 'google',
    type: 'text',
    protocols: ['gemini', 'openai-chat'],
    contextTokens: 1_000_000,
    released: '2026-06-03',
    description: {
      zh: 'Google 成本最低的正式版模型，高并发场景首选。',
      en: "Google's lowest-cost GA model, the first pick for high-concurrency workloads.",
    },
    official: { input: 0.25, output: 1.5, cacheRead: 0.0625 },
    longContext: null,
    image: null,
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    type: 'text',
    protocols: ['gemini', 'openai-chat'],
    contextTokens: 1_000_000,
    released: '2025-06-17',
    description: {
      zh: '成熟稳定的上一代旗舰，长上下文推理表现可靠。',
      en: 'A mature previous-generation flagship with reliable long-context reasoning.',
    },
    official: { input: 1.25, output: 10, cacheRead: 0.3125 },
    longContext: { threshold: 200_000, input: 2.5, output: 15 },
    image: null,
  },

  // ---------- DeepSeek ----------
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    provider: 'deepseek',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 1_000_000,
    released: '2026-07-08',
    description: {
      zh: 'DeepSeek 旗舰推理模型，百万上下文，成本极低。',
      en: "DeepSeek's flagship reasoning model with a 1M context at a very low cost.",
    },
    official: { input: 1.32, output: 3.96, cacheRead: 0.132 },
    longContext: null,
    image: null,
  },
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    provider: 'deepseek',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 1_000_000,
    released: '2026-07-08',
    description: {
      zh: '更快更省的 V4，支持思考与非思考双模式。',
      en: 'A faster, cheaper V4 with both thinking and non-thinking modes.',
    },
    official: { input: 0.44, output: 1.32, cacheRead: 0.044 },
    longContext: null,
    image: null,
  },

  // ---------- 国内厂商 ----------
  {
    id: 'kimi-k3',
    name: 'Kimi K3',
    provider: 'moonshot',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 1_000_000,
    released: '2026-08-28',
    description: {
      zh: '月之暗面开源旗舰，原生视觉，思考模式常开。',
      en: "Moonshot's open-weight flagship with native vision and always-on thinking.",
    },
    official: { input: 3, output: 15, cacheRead: 0.3 },
    longContext: null,
    image: null,
  },
  {
    id: 'glm-5.2',
    name: 'GLM-5.2',
    provider: 'zhipu',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 1_000_000,
    released: '2026-08-12',
    description: {
      zh: '智谱百万上下文旗舰，长链路编码能力强。',
      en: "Zhipu's 1M-context flagship, strong at long-chain coding.",
    },
    official: { input: 1.4, output: 4.4, cacheRead: 0.14 },
    longContext: null,
    image: null,
  },
  {
    id: 'minimax-m3',
    name: 'MiniMax M3',
    provider: 'minimax',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 1_000_000,
    released: '2026-07-30',
    description: {
      zh: 'MiniMax 新一代旗舰，长上下文与工具调用表现均衡。',
      en: "MiniMax's new flagship, balanced across long context and tool use.",
    },
    official: { input: 0.6, output: 2.4, cacheRead: 0.06 },
    longContext: { threshold: 512_000, input: 1.2, output: 4.8 },
    image: null,
  },
  {
    id: 'qwen3.6-max',
    name: 'Qwen3.6 Max',
    provider: 'qwen',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 256_000,
    released: '2026-09-02',
    description: {
      zh: '通义千问旗舰，中文理解与代码生成表现出色。',
      en: "Qwen's flagship, excellent at Chinese understanding and code generation.",
    },
    official: { input: 1.6, output: 6.4, cacheRead: 0.16 },
    longContext: null,
    image: null,
  },

  // ---------- 生图 ----------
  {
    id: 'gpt-image-2.5-sunburst',
    name: 'GPT Image 2.5 Sunburst',
    provider: 'openai',
    type: 'image',
    protocols: ['openai-images'],
    contextTokens: null,
    released: '2026-09-05',
    description: {
      zh: '能力最强的 GPT 图像模型，擅长复杂构图与精细编辑。',
      en: 'The most capable GPT image model, strong at complex composition and fine edits.',
    },
    official: null,
    longContext: null,
    image: { kind: 'per-token', perMTokens: 30 },
  },
  {
    id: 'gpt-image-2.5-flare',
    name: 'GPT Image 2.5 Flare',
    provider: 'openai',
    type: 'image',
    protocols: ['openai-images'],
    contextTokens: null,
    released: '2026-09-05',
    description: {
      zh: '出图最快的高质量图像模型，适合批量生成。',
      en: 'The fastest high-quality image model, suited to batch generation.',
    },
    official: null,
    longContext: null,
    image: { kind: 'per-token', perMTokens: 30 },
  },
  {
    id: 'gpt-image-2',
    name: 'GPT Image 2',
    provider: 'openai',
    type: 'image',
    protocols: ['openai-images'],
    contextTokens: null,
    released: '2026-05-12',
    description: {
      zh: '高保真图像生成与编辑，文字渲染清晰。',
      en: 'High-fidelity image generation and editing with crisp text rendering.',
    },
    official: null,
    longContext: null,
    image: {
      kind: 'per-image',
      resolutions: [
        { label: '1K', price: 0.04 },
        { label: '2K', price: 0.134 },
        { label: '4K', price: 0.24 },
      ],
    },
  },
  {
    id: 'gemini-3-pro-image',
    name: 'Gemini 3 Pro Image',
    provider: 'google',
    type: 'image',
    protocols: ['gemini', 'openai-images'],
    contextTokens: null,
    released: '2025-11-20',
    description: {
      zh: 'Nano Banana Pro，Google 最强的图像生成与编辑模型，支持 4K 输出。',
      en: "Nano Banana Pro — Google's most capable image generation and editing model, with 4K output.",
    },
    official: null,
    longContext: null,
    image: {
      kind: 'per-image',
      resolutions: [
        { label: '2K', price: 0.134 },
        { label: '4K', price: 0.24 },
      ],
    },
  },
  {
    id: 'gemini-3.1-flash-image',
    name: 'Gemini 3.1 Flash Image',
    provider: 'google',
    type: 'image',
    protocols: ['gemini', 'openai-images'],
    contextTokens: null,
    released: '2026-03-10',
    description: {
      zh: 'Nano Banana 2，速度与画质兼顾的默认图像模型。',
      en: 'Nano Banana 2 — the default image model balancing speed and quality.',
    },
    official: null,
    longContext: null,
    image: { kind: 'per-token', perMTokens: 60 },
  },
  {
    id: 'gemini-3.1-flash-lite-image',
    name: 'Gemini 3.1 Flash Lite Image',
    provider: 'google',
    type: 'image',
    protocols: ['gemini', 'openai-images'],
    contextTokens: null,
    released: '2026-06-24',
    description: {
      zh: 'Nano Banana 2 Lite，家族中最快最省的一档。',
      en: 'Nano Banana 2 Lite — the fastest, most economical tier in the family.',
    },
    official: null,
    longContext: null,
    image: { kind: 'per-token', perMTokens: 30 },
  },
  {
    id: 'gemini-2.5-flash-image',
    name: 'Gemini 2.5 Flash Image',
    provider: 'google',
    type: 'image',
    protocols: ['gemini', 'openai-images'],
    contextTokens: null,
    released: '2025-08-26',
    description: {
      zh: 'Nano Banana，快速图像生成与编辑。',
      en: 'Nano Banana — fast image generation and editing.',
    },
    official: null,
    longContext: null,
    image: { kind: 'per-token', perMTokens: 30 },
  },
];

const MODEL_BY_ID = new Map(MODELS.map((model) => [model.id, model]));

/** 按调用名取模型；占位数据里的模型名都来自本目录，找不到说明数据写错了 */
export function getModel(id: string): Model {
  const model = MODEL_BY_ID.get(id);
  if (!model) throw new Error(`unknown model: ${id}`);
  return model;
}
