import type { Model } from './types';

/**
 * 模型目录（占位数据）。官方价单位：美元 / 百万 Token；生图按张为美元 / 张。
 * 本站价格 = 官方价 × 所选版本的分组倍率（见 editions.ts），这里只放官方价。
 * 型号与官方价参考 onehop.ai 2026-10-03 公开价目推算，替换时只改这里。
 */
export const MODELS: readonly Model[] = [
  // ---------- OpenAI 文本 ----------
  {
    id: 'gpt-6-astra',
    name: 'GPT-6 Astra',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    official: { input: 10, output: 50, cacheRead: 1 },
    longContext: { threshold: 272_000, input: 20, output: 75 },
    image: null,
  },
  {
    id: 'gpt-6-sol',
    name: 'GPT-6 Sol',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    official: { input: 2, output: 10, cacheRead: 0.2 },
    longContext: { threshold: 272_000, input: 4, output: 15 },
    image: null,
  },
  {
    id: 'gpt-6-luna',
    name: 'GPT-6 Luna',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    official: { input: 0.1, output: 0.5, cacheRead: 0.01 },
    longContext: { threshold: 272_000, input: 0.2, output: 0.75 },
    image: null,
  },
  {
    id: 'gpt-5.6-sol',
    name: 'GPT-5.6 Sol',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    official: { input: 4, output: 20, cacheRead: 0.4 },
    longContext: { threshold: 272_000, input: 8, output: 30 },
    image: null,
  },
  {
    id: 'gpt-5.6-terra',
    name: 'GPT-5.6 Terra',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    official: { input: 2, output: 12, cacheRead: 0.2 },
    longContext: { threshold: 272_000, input: 4, output: 18 },
    image: null,
  },
  {
    id: 'gpt-5.6-luna',
    name: 'GPT-5.6 Luna',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_050_000,
    official: { input: 0.2, output: 1.2, cacheRead: 0.02 },
    longContext: { threshold: 272_000, input: 0.4, output: 1.8 },
    image: null,
  },
  {
    id: 'gpt-5.5',
    name: 'GPT-5.5',
    provider: 'openai',
    type: 'text',
    protocols: ['openai-chat', 'openai-responses'],
    contextTokens: 1_000_000,
    official: { input: 5, output: 30, cacheRead: 0.5 },
    longContext: { threshold: 272_000, input: 10, output: 45 },
    image: null,
  },

  // ---------- Anthropic ----------
  {
    id: 'claude-fable-5-1',
    name: 'Claude Fable 5.1',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 1_000_000,
    official: { input: 10, output: 50, cacheRead: 1 },
    longContext: null,
    image: null,
  },
  {
    id: 'claude-opus-5',
    name: 'Claude Opus 5',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 1_000_000,
    official: { input: 5, output: 25, cacheRead: 0.5 },
    longContext: null,
    image: null,
  },
  {
    id: 'claude-sonnet-5-5',
    name: 'Claude Sonnet 5.5',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 1_000_000,
    official: { input: 2, output: 10, cacheRead: 0.2 },
    longContext: null,
    image: null,
  },
  {
    id: 'claude-sonnet-5',
    name: 'Claude Sonnet 5',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 1_000_000,
    official: { input: 3, output: 15, cacheRead: 0.3 },
    longContext: null,
    image: null,
  },
  {
    id: 'claude-opus-4-8',
    name: 'Claude Opus 4.8',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 1_000_000,
    official: { input: 5, output: 25, cacheRead: 0.5 },
    longContext: null,
    image: null,
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    type: 'text',
    protocols: ['anthropic-messages', 'openai-chat'],
    contextTokens: 200_000,
    official: { input: 1, output: 5, cacheRead: 0.1 },
    longContext: null,
    image: null,
  },

  // ---------- Google 文本 ----------
  {
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    provider: 'google',
    type: 'text',
    protocols: ['gemini', 'openai-chat'],
    contextTokens: 1_000_000,
    official: { input: 1.5, output: 9, cacheRead: 0.375 },
    longContext: null,
    image: null,
  },
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro',
    provider: 'google',
    type: 'text',
    protocols: ['gemini', 'openai-chat'],
    contextTokens: 1_000_000,
    official: { input: 2, output: 12, cacheRead: 0.5 },
    longContext: { threshold: 200_000, input: 4, output: 18 },
    image: null,
  },
  {
    id: 'gemini-3.1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    provider: 'google',
    type: 'text',
    protocols: ['gemini', 'openai-chat'],
    contextTokens: 1_000_000,
    official: { input: 0.25, output: 1.5, cacheRead: 0.0625 },
    longContext: null,
    image: null,
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    type: 'text',
    protocols: ['gemini', 'openai-chat'],
    contextTokens: 1_000_000,
    official: { input: 1.25, output: 10, cacheRead: 0.3125 },
    longContext: { threshold: 200_000, input: 2.5, output: 15 },
    image: null,
  },

  // ---------- DeepSeek ----------
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    provider: 'deepseek',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 1_000_000,
    official: { input: 1.32, output: 3.96, cacheRead: 0.132 },
    longContext: null,
    image: null,
  },
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    provider: 'deepseek',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 1_000_000,
    official: { input: 0.44, output: 1.32, cacheRead: 0.044 },
    longContext: null,
    image: null,
  },

  // ---------- 国内厂商 ----------
  {
    id: 'kimi-k3',
    name: 'Kimi K3',
    provider: 'moonshot',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 1_000_000,
    official: { input: 3, output: 15, cacheRead: 0.3 },
    longContext: null,
    image: null,
  },
  {
    id: 'glm-5.2',
    name: 'GLM-5.2',
    provider: 'zhipu',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 1_000_000,
    official: { input: 1.4, output: 4.4, cacheRead: 0.14 },
    longContext: null,
    image: null,
  },
  {
    id: 'minimax-m3',
    name: 'MiniMax M3',
    provider: 'minimax',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 1_000_000,
    official: { input: 0.6, output: 2.4, cacheRead: 0.06 },
    longContext: { threshold: 512_000, input: 1.2, output: 4.8 },
    image: null,
  },
  {
    id: 'qwen3.6-max',
    name: 'Qwen3.6 Max',
    provider: 'qwen',
    type: 'text',
    protocols: ['openai-chat', 'anthropic-messages'],
    contextTokens: 256_000,
    official: { input: 1.6, output: 6.4, cacheRead: 0.16 },
    longContext: null,
    image: null,
  },

  // ---------- 生图 ----------
  {
    id: 'gpt-image-2.5-sunburst',
    name: 'GPT Image 2.5 Sunburst',
    provider: 'openai',
    type: 'image',
    protocols: ['openai-images'],
    contextTokens: null,
    official: null,
    longContext: null,
    image: { kind: 'per-token', perMTokens: 30 },
  },
  {
    id: 'gpt-image-2.5-flare',
    name: 'GPT Image 2.5 Flare',
    provider: 'openai',
    type: 'image',
    protocols: ['openai-images'],
    contextTokens: null,
    official: null,
    longContext: null,
    image: { kind: 'per-token', perMTokens: 30 },
  },
  {
    id: 'gpt-image-2',
    name: 'GPT Image 2',
    provider: 'openai',
    type: 'image',
    protocols: ['openai-images'],
    contextTokens: null,
    official: null,
    longContext: null,
    image: {
      kind: 'per-image',
      resolutions: [
        { label: '1K', price: 0.04 },
        { label: '2K', price: 0.134 },
        { label: '4K', price: 0.24 },
      ],
    },
  },
  {
    id: 'gemini-3-pro-image',
    name: 'Gemini 3 Pro Image',
    provider: 'google',
    type: 'image',
    protocols: ['gemini', 'openai-images'],
    contextTokens: null,
    official: null,
    longContext: null,
    image: {
      kind: 'per-image',
      resolutions: [
        { label: '2K', price: 0.134 },
        { label: '4K', price: 0.24 },
      ],
    },
  },
  {
    id: 'gemini-3.1-flash-image',
    name: 'Gemini 3.1 Flash Image',
    provider: 'google',
    type: 'image',
    protocols: ['gemini', 'openai-images'],
    contextTokens: null,
    official: null,
    longContext: null,
    image: { kind: 'per-token', perMTokens: 60 },
  },
  {
    id: 'gemini-3.1-flash-lite-image',
    name: 'Gemini 3.1 Flash Lite Image',
    provider: 'google',
    type: 'image',
    protocols: ['gemini', 'openai-images'],
    contextTokens: null,
    official: null,
    longContext: null,
    image: { kind: 'per-token', perMTokens: 30 },
  },
  {
    id: 'gemini-2.5-flash-image',
    name: 'Gemini 2.5 Flash Image',
    provider: 'google',
    type: 'image',
    protocols: ['gemini', 'openai-images'],
    contextTokens: null,
    official: null,
    longContext: null,
    image: { kind: 'per-token', perMTokens: 30 },
  },
];

const MODEL_BY_ID = new Map(MODELS.map((model) => [model.id, model]));

/** 按调用名取模型；占位数据里的模型名都来自本目录，找不到说明数据写错了 */
export function getModel(id: string): Model {
  const model = MODEL_BY_ID.get(id);
  if (!model) throw new Error(`unknown model: ${id}`);
  return model;
}
