// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/organizationallowedgroup"
)

// OrganizationAllowedGroup is the model entity for the OrganizationAllowedGroup schema.
type OrganizationAllowedGroup struct {
	config `json:"-"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID int64 `json:"organization_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrganizationAllowedGroupQuery when eager-loading is set.
	Edges        OrganizationAllowedGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrganizationAllowedGroupEdges holds the relations/edges for other nodes in the graph.
type OrganizationAllowedGroupEdges struct {
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationAllowedGroupEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationAllowedGroupEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrganizationAllowedGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case organizationallowedgroup.FieldOrganizationID, organizationallowedgroup.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case organizationallowedgroup.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrganizationAllowedGroup fields.
func (_m *OrganizationAllowedGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case organizationallowedgroup.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = value.Int64
			}
		case organizationallowedgroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case organizationallowedgroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrganizationAllowedGroup.
// This includes values selected through modifiers, order, etc.
func (_m *OrganizationAllowedGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrganization queries the "organization" edge of the OrganizationAllowedGroup entity.
func (_m *OrganizationAllowedGroup) QueryOrganization() *OrganizationQuery {
	return NewOrganizationAllowedGroupClient(_m.config).QueryOrganization(_m)
}

// QueryGroup queries the "group" edge of the OrganizationAllowedGroup entity.
func (_m *OrganizationAllowedGroup) QueryGroup() *GroupQuery {
	return NewOrganizationAllowedGroupClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this OrganizationAllowedGroup.
// Note that you need to call OrganizationAllowedGroup.Unwrap() before calling this method if this OrganizationAllowedGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrganizationAllowedGroup) Update() *OrganizationAllowedGroupUpdateOne {
	return NewOrganizationAllowedGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrganizationAllowedGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrganizationAllowedGroup) Unwrap() *OrganizationAllowedGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrganizationAllowedGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrganizationAllowedGroup) String() string {
	var builder strings.Builder
	builder.WriteString("OrganizationAllowedGroup(")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OrganizationAllowedGroups is a parsable slice of OrganizationAllowedGroup.
type OrganizationAllowedGroups []*OrganizationAllowedGroup
