// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/organizationquotarequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OrganizationQuotaRequestUpdate is the builder for updating OrganizationQuotaRequest entities.
type OrganizationQuotaRequestUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationQuotaRequestMutation
}

// Where appends a list predicates to the OrganizationQuotaRequestUpdate builder.
func (_u *OrganizationQuotaRequestUpdate) Where(ps ...predicate.OrganizationQuotaRequest) *OrganizationQuotaRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationQuotaRequestUpdate) SetUpdatedAt(v time.Time) *OrganizationQuotaRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *OrganizationQuotaRequestUpdate) SetOrganizationID(v int64) *OrganizationQuotaRequestUpdate {
	_u.mutation.ResetOrganizationID()
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableOrganizationID(v *int64) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// AddOrganizationID adds value to the "organization_id" field.
func (_u *OrganizationQuotaRequestUpdate) AddOrganizationID(v int64) *OrganizationQuotaRequestUpdate {
	_u.mutation.AddOrganizationID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrganizationQuotaRequestUpdate) SetUserID(v int64) *OrganizationQuotaRequestUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableUserID(v *int64) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OrganizationQuotaRequestUpdate) AddUserID(v int64) *OrganizationQuotaRequestUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *OrganizationQuotaRequestUpdate) SetAmount(v float64) *OrganizationQuotaRequestUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableAmount(v *float64) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *OrganizationQuotaRequestUpdate) AddAmount(v float64) *OrganizationQuotaRequestUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *OrganizationQuotaRequestUpdate) SetReason(v string) *OrganizationQuotaRequestUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableReason(v *string) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *OrganizationQuotaRequestUpdate) ClearReason() *OrganizationQuotaRequestUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrganizationQuotaRequestUpdate) SetStatus(v string) *OrganizationQuotaRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableStatus(v *string) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGrantSource sets the "grant_source" field.
func (_u *OrganizationQuotaRequestUpdate) SetGrantSource(v string) *OrganizationQuotaRequestUpdate {
	_u.mutation.SetGrantSource(v)
	return _u
}

// SetNillableGrantSource sets the "grant_source" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableGrantSource(v *string) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetGrantSource(*v)
	}
	return _u
}

// ClearGrantSource clears the value of the "grant_source" field.
func (_u *OrganizationQuotaRequestUpdate) ClearGrantSource() *OrganizationQuotaRequestUpdate {
	_u.mutation.ClearGrantSource()
	return _u
}

// SetGrantedAmount sets the "granted_amount" field.
func (_u *OrganizationQuotaRequestUpdate) SetGrantedAmount(v float64) *OrganizationQuotaRequestUpdate {
	_u.mutation.ResetGrantedAmount()
	_u.mutation.SetGrantedAmount(v)
	return _u
}

// SetNillableGrantedAmount sets the "granted_amount" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableGrantedAmount(v *float64) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetGrantedAmount(*v)
	}
	return _u
}

// AddGrantedAmount adds value to the "granted_amount" field.
func (_u *OrganizationQuotaRequestUpdate) AddGrantedAmount(v float64) *OrganizationQuotaRequestUpdate {
	_u.mutation.AddGrantedAmount(v)
	return _u
}

// ClearGrantedAmount clears the value of the "granted_amount" field.
func (_u *OrganizationQuotaRequestUpdate) ClearGrantedAmount() *OrganizationQuotaRequestUpdate {
	_u.mutation.ClearGrantedAmount()
	return _u
}

// SetSnapshotMode sets the "snapshot_mode" field.
func (_u *OrganizationQuotaRequestUpdate) SetSnapshotMode(v string) *OrganizationQuotaRequestUpdate {
	_u.mutation.SetSnapshotMode(v)
	return _u
}

// SetNillableSnapshotMode sets the "snapshot_mode" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableSnapshotMode(v *string) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetSnapshotMode(*v)
	}
	return _u
}

// SetSnapshotLimit sets the "snapshot_limit" field.
func (_u *OrganizationQuotaRequestUpdate) SetSnapshotLimit(v float64) *OrganizationQuotaRequestUpdate {
	_u.mutation.ResetSnapshotLimit()
	_u.mutation.SetSnapshotLimit(v)
	return _u
}

// SetNillableSnapshotLimit sets the "snapshot_limit" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableSnapshotLimit(v *float64) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetSnapshotLimit(*v)
	}
	return _u
}

// AddSnapshotLimit adds value to the "snapshot_limit" field.
func (_u *OrganizationQuotaRequestUpdate) AddSnapshotLimit(v float64) *OrganizationQuotaRequestUpdate {
	_u.mutation.AddSnapshotLimit(v)
	return _u
}

// ClearSnapshotLimit clears the value of the "snapshot_limit" field.
func (_u *OrganizationQuotaRequestUpdate) ClearSnapshotLimit() *OrganizationQuotaRequestUpdate {
	_u.mutation.ClearSnapshotLimit()
	return _u
}

// SetSnapshotUsed sets the "snapshot_used" field.
func (_u *OrganizationQuotaRequestUpdate) SetSnapshotUsed(v float64) *OrganizationQuotaRequestUpdate {
	_u.mutation.ResetSnapshotUsed()
	_u.mutation.SetSnapshotUsed(v)
	return _u
}

// SetNillableSnapshotUsed sets the "snapshot_used" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableSnapshotUsed(v *float64) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetSnapshotUsed(*v)
	}
	return _u
}

// AddSnapshotUsed adds value to the "snapshot_used" field.
func (_u *OrganizationQuotaRequestUpdate) AddSnapshotUsed(v float64) *OrganizationQuotaRequestUpdate {
	_u.mutation.AddSnapshotUsed(v)
	return _u
}

// SetReviewerUserID sets the "reviewer_user_id" field.
func (_u *OrganizationQuotaRequestUpdate) SetReviewerUserID(v int64) *OrganizationQuotaRequestUpdate {
	_u.mutation.ResetReviewerUserID()
	_u.mutation.SetReviewerUserID(v)
	return _u
}

// SetNillableReviewerUserID sets the "reviewer_user_id" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableReviewerUserID(v *int64) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetReviewerUserID(*v)
	}
	return _u
}

// AddReviewerUserID adds value to the "reviewer_user_id" field.
func (_u *OrganizationQuotaRequestUpdate) AddReviewerUserID(v int64) *OrganizationQuotaRequestUpdate {
	_u.mutation.AddReviewerUserID(v)
	return _u
}

// ClearReviewerUserID clears the value of the "reviewer_user_id" field.
func (_u *OrganizationQuotaRequestUpdate) ClearReviewerUserID() *OrganizationQuotaRequestUpdate {
	_u.mutation.ClearReviewerUserID()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *OrganizationQuotaRequestUpdate) SetReviewedAt(v time.Time) *OrganizationQuotaRequestUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableReviewedAt(v *time.Time) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *OrganizationQuotaRequestUpdate) ClearReviewedAt() *OrganizationQuotaRequestUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewNote sets the "review_note" field.
func (_u *OrganizationQuotaRequestUpdate) SetReviewNote(v string) *OrganizationQuotaRequestUpdate {
	_u.mutation.SetReviewNote(v)
	return _u
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdate) SetNillableReviewNote(v *string) *OrganizationQuotaRequestUpdate {
	if v != nil {
		_u.SetReviewNote(*v)
	}
	return _u
}

// ClearReviewNote clears the value of the "review_note" field.
func (_u *OrganizationQuotaRequestUpdate) ClearReviewNote() *OrganizationQuotaRequestUpdate {
	_u.mutation.ClearReviewNote()
	return _u
}

// Mutation returns the OrganizationQuotaRequestMutation object of the builder.
func (_u *OrganizationQuotaRequestUpdate) Mutation() *OrganizationQuotaRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrganizationQuotaRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationQuotaRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrganizationQuotaRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationQuotaRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationQuotaRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := organizationquotarequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationQuotaRequestUpdate) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := organizationquotarequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := organizationquotarequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GrantSource(); ok {
		if err := organizationquotarequest.GrantSourceValidator(v); err != nil {
			return &ValidationError{Name: "grant_source", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.grant_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SnapshotMode(); ok {
		if err := organizationquotarequest.SnapshotModeValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_mode", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.snapshot_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReviewNote(); ok {
		if err := organizationquotarequest.ReviewNoteValidator(v); err != nil {
			return &ValidationError{Name: "review_note", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.review_note": %w`, err)}
		}
	}
	return nil
}

func (_u *OrganizationQuotaRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationquotarequest.Table, organizationquotarequest.Columns, sqlgraph.NewFieldSpec(organizationquotarequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationquotarequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(organizationquotarequest.FieldOrganizationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrganizationID(); ok {
		_spec.AddField(organizationquotarequest.FieldOrganizationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(organizationquotarequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(organizationquotarequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(organizationquotarequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(organizationquotarequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(organizationquotarequest.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(organizationquotarequest.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(organizationquotarequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantSource(); ok {
		_spec.SetField(organizationquotarequest.FieldGrantSource, field.TypeString, value)
	}
	if _u.mutation.GrantSourceCleared() {
		_spec.ClearField(organizationquotarequest.FieldGrantSource, field.TypeString)
	}
	if value, ok := _u.mutation.GrantedAmount(); ok {
		_spec.SetField(organizationquotarequest.FieldGrantedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrantedAmount(); ok {
		_spec.AddField(organizationquotarequest.FieldGrantedAmount, field.TypeFloat64, value)
	}
	if _u.mutation.GrantedAmountCleared() {
		_spec.ClearField(organizationquotarequest.FieldGrantedAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SnapshotMode(); ok {
		_spec.SetField(organizationquotarequest.FieldSnapshotMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.SnapshotLimit(); ok {
		_spec.SetField(organizationquotarequest.FieldSnapshotLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSnapshotLimit(); ok {
		_spec.AddField(organizationquotarequest.FieldSnapshotLimit, field.TypeFloat64, value)
	}
	if _u.mutation.SnapshotLimitCleared() {
		_spec.ClearField(organizationquotarequest.FieldSnapshotLimit, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SnapshotUsed(); ok {
		_spec.SetField(organizationquotarequest.FieldSnapshotUsed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSnapshotUsed(); ok {
		_spec.AddField(organizationquotarequest.FieldSnapshotUsed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReviewerUserID(); ok {
		_spec.SetField(organizationquotarequest.FieldReviewerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewerUserID(); ok {
		_spec.AddField(organizationquotarequest.FieldReviewerUserID, field.TypeInt64, value)
	}
	if _u.mutation.ReviewerUserIDCleared() {
		_spec.ClearField(organizationquotarequest.FieldReviewerUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(organizationquotarequest.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(organizationquotarequest.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewNote(); ok {
		_spec.SetField(organizationquotarequest.FieldReviewNote, field.TypeString, value)
	}
	if _u.mutation.ReviewNoteCleared() {
		_spec.ClearField(organizationquotarequest.FieldReviewNote, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationquotarequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrganizationQuotaRequestUpdateOne is the builder for updating a single OrganizationQuotaRequest entity.
type OrganizationQuotaRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationQuotaRequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetUpdatedAt(v time.Time) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetOrganizationID(v int64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ResetOrganizationID()
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableOrganizationID(v *int64) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// AddOrganizationID adds value to the "organization_id" field.
func (_u *OrganizationQuotaRequestUpdateOne) AddOrganizationID(v int64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.AddOrganizationID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetUserID(v int64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableUserID(v *int64) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OrganizationQuotaRequestUpdateOne) AddUserID(v int64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetAmount(v float64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableAmount(v *float64) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *OrganizationQuotaRequestUpdateOne) AddAmount(v float64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetReason(v string) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableReason(v *string) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *OrganizationQuotaRequestUpdateOne) ClearReason() *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetStatus(v string) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableStatus(v *string) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGrantSource sets the "grant_source" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetGrantSource(v string) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.SetGrantSource(v)
	return _u
}

// SetNillableGrantSource sets the "grant_source" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableGrantSource(v *string) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetGrantSource(*v)
	}
	return _u
}

// ClearGrantSource clears the value of the "grant_source" field.
func (_u *OrganizationQuotaRequestUpdateOne) ClearGrantSource() *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ClearGrantSource()
	return _u
}

// SetGrantedAmount sets the "granted_amount" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetGrantedAmount(v float64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ResetGrantedAmount()
	_u.mutation.SetGrantedAmount(v)
	return _u
}

// SetNillableGrantedAmount sets the "granted_amount" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableGrantedAmount(v *float64) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetGrantedAmount(*v)
	}
	return _u
}

// AddGrantedAmount adds value to the "granted_amount" field.
func (_u *OrganizationQuotaRequestUpdateOne) AddGrantedAmount(v float64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.AddGrantedAmount(v)
	return _u
}

// ClearGrantedAmount clears the value of the "granted_amount" field.
func (_u *OrganizationQuotaRequestUpdateOne) ClearGrantedAmount() *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ClearGrantedAmount()
	return _u
}

// SetSnapshotMode sets the "snapshot_mode" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetSnapshotMode(v string) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.SetSnapshotMode(v)
	return _u
}

// SetNillableSnapshotMode sets the "snapshot_mode" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableSnapshotMode(v *string) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetSnapshotMode(*v)
	}
	return _u
}

// SetSnapshotLimit sets the "snapshot_limit" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetSnapshotLimit(v float64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ResetSnapshotLimit()
	_u.mutation.SetSnapshotLimit(v)
	return _u
}

// SetNillableSnapshotLimit sets the "snapshot_limit" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableSnapshotLimit(v *float64) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetSnapshotLimit(*v)
	}
	return _u
}

// AddSnapshotLimit adds value to the "snapshot_limit" field.
func (_u *OrganizationQuotaRequestUpdateOne) AddSnapshotLimit(v float64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.AddSnapshotLimit(v)
	return _u
}

// ClearSnapshotLimit clears the value of the "snapshot_limit" field.
func (_u *OrganizationQuotaRequestUpdateOne) ClearSnapshotLimit() *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ClearSnapshotLimit()
	return _u
}

// SetSnapshotUsed sets the "snapshot_used" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetSnapshotUsed(v float64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ResetSnapshotUsed()
	_u.mutation.SetSnapshotUsed(v)
	return _u
}

// SetNillableSnapshotUsed sets the "snapshot_used" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableSnapshotUsed(v *float64) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetSnapshotUsed(*v)
	}
	return _u
}

// AddSnapshotUsed adds value to the "snapshot_used" field.
func (_u *OrganizationQuotaRequestUpdateOne) AddSnapshotUsed(v float64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.AddSnapshotUsed(v)
	return _u
}

// SetReviewerUserID sets the "reviewer_user_id" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetReviewerUserID(v int64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ResetReviewerUserID()
	_u.mutation.SetReviewerUserID(v)
	return _u
}

// SetNillableReviewerUserID sets the "reviewer_user_id" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableReviewerUserID(v *int64) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetReviewerUserID(*v)
	}
	return _u
}

// AddReviewerUserID adds value to the "reviewer_user_id" field.
func (_u *OrganizationQuotaRequestUpdateOne) AddReviewerUserID(v int64) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.AddReviewerUserID(v)
	return _u
}

// ClearReviewerUserID clears the value of the "reviewer_user_id" field.
func (_u *OrganizationQuotaRequestUpdateOne) ClearReviewerUserID() *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ClearReviewerUserID()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetReviewedAt(v time.Time) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableReviewedAt(v *time.Time) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *OrganizationQuotaRequestUpdateOne) ClearReviewedAt() *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewNote sets the "review_note" field.
func (_u *OrganizationQuotaRequestUpdateOne) SetReviewNote(v string) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.SetReviewNote(v)
	return _u
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_u *OrganizationQuotaRequestUpdateOne) SetNillableReviewNote(v *string) *OrganizationQuotaRequestUpdateOne {
	if v != nil {
		_u.SetReviewNote(*v)
	}
	return _u
}

// ClearReviewNote clears the value of the "review_note" field.
func (_u *OrganizationQuotaRequestUpdateOne) ClearReviewNote() *OrganizationQuotaRequestUpdateOne {
	_u.mutation.ClearReviewNote()
	return _u
}

// Mutation returns the OrganizationQuotaRequestMutation object of the builder.
func (_u *OrganizationQuotaRequestUpdateOne) Mutation() *OrganizationQuotaRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrganizationQuotaRequestUpdate builder.
func (_u *OrganizationQuotaRequestUpdateOne) Where(ps ...predicate.OrganizationQuotaRequest) *OrganizationQuotaRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrganizationQuotaRequestUpdateOne) Select(field string, fields ...string) *OrganizationQuotaRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrganizationQuotaRequest entity.
func (_u *OrganizationQuotaRequestUpdateOne) Save(ctx context.Context) (*OrganizationQuotaRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationQuotaRequestUpdateOne) SaveX(ctx context.Context) *OrganizationQuotaRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrganizationQuotaRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationQuotaRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationQuotaRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := organizationquotarequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationQuotaRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := organizationquotarequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := organizationquotarequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GrantSource(); ok {
		if err := organizationquotarequest.GrantSourceValidator(v); err != nil {
			return &ValidationError{Name: "grant_source", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.grant_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SnapshotMode(); ok {
		if err := organizationquotarequest.SnapshotModeValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_mode", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.snapshot_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReviewNote(); ok {
		if err := organizationquotarequest.ReviewNoteValidator(v); err != nil {
			return &ValidationError{Name: "review_note", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.review_note": %w`, err)}
		}
	}
	return nil
}

func (_u *OrganizationQuotaRequestUpdateOne) sqlSave(ctx context.Context) (_node *OrganizationQuotaRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationquotarequest.Table, organizationquotarequest.Columns, sqlgraph.NewFieldSpec(organizationquotarequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrganizationQuotaRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationquotarequest.FieldID)
		for _, f := range fields {
			if !organizationquotarequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organizationquotarequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationquotarequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(organizationquotarequest.FieldOrganizationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrganizationID(); ok {
		_spec.AddField(organizationquotarequest.FieldOrganizationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(organizationquotarequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(organizationquotarequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(organizationquotarequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(organizationquotarequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(organizationquotarequest.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(organizationquotarequest.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(organizationquotarequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantSource(); ok {
		_spec.SetField(organizationquotarequest.FieldGrantSource, field.TypeString, value)
	}
	if _u.mutation.GrantSourceCleared() {
		_spec.ClearField(organizationquotarequest.FieldGrantSource, field.TypeString)
	}
	if value, ok := _u.mutation.GrantedAmount(); ok {
		_spec.SetField(organizationquotarequest.FieldGrantedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrantedAmount(); ok {
		_spec.AddField(organizationquotarequest.FieldGrantedAmount, field.TypeFloat64, value)
	}
	if _u.mutation.GrantedAmountCleared() {
		_spec.ClearField(organizationquotarequest.FieldGrantedAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SnapshotMode(); ok {
		_spec.SetField(organizationquotarequest.FieldSnapshotMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.SnapshotLimit(); ok {
		_spec.SetField(organizationquotarequest.FieldSnapshotLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSnapshotLimit(); ok {
		_spec.AddField(organizationquotarequest.FieldSnapshotLimit, field.TypeFloat64, value)
	}
	if _u.mutation.SnapshotLimitCleared() {
		_spec.ClearField(organizationquotarequest.FieldSnapshotLimit, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SnapshotUsed(); ok {
		_spec.SetField(organizationquotarequest.FieldSnapshotUsed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSnapshotUsed(); ok {
		_spec.AddField(organizationquotarequest.FieldSnapshotUsed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReviewerUserID(); ok {
		_spec.SetField(organizationquotarequest.FieldReviewerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewerUserID(); ok {
		_spec.AddField(organizationquotarequest.FieldReviewerUserID, field.TypeInt64, value)
	}
	if _u.mutation.ReviewerUserIDCleared() {
		_spec.ClearField(organizationquotarequest.FieldReviewerUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(organizationquotarequest.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(organizationquotarequest.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewNote(); ok {
		_spec.SetField(organizationquotarequest.FieldReviewNote, field.TypeString, value)
	}
	if _u.mutation.ReviewNoteCleared() {
		_spec.ClearField(organizationquotarequest.FieldReviewNote, field.TypeString)
	}
	_node = &OrganizationQuotaRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationquotarequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
