// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/organizationallowedgroup"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OrganizationAllowedGroupUpdate is the builder for updating OrganizationAllowedGroup entities.
type OrganizationAllowedGroupUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationAllowedGroupMutation
}

// Where appends a list predicates to the OrganizationAllowedGroupUpdate builder.
func (_u *OrganizationAllowedGroupUpdate) Where(ps ...predicate.OrganizationAllowedGroup) *OrganizationAllowedGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *OrganizationAllowedGroupUpdate) SetOrganizationID(v int64) *OrganizationAllowedGroupUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *OrganizationAllowedGroupUpdate) SetNillableOrganizationID(v *int64) *OrganizationAllowedGroupUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OrganizationAllowedGroupUpdate) SetGroupID(v int64) *OrganizationAllowedGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OrganizationAllowedGroupUpdate) SetNillableGroupID(v *int64) *OrganizationAllowedGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *OrganizationAllowedGroupUpdate) SetOrganization(v *Organization) *OrganizationAllowedGroupUpdate {
	return _u.SetOrganizationID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *OrganizationAllowedGroupUpdate) SetGroup(v *Group) *OrganizationAllowedGroupUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the OrganizationAllowedGroupMutation object of the builder.
func (_u *OrganizationAllowedGroupUpdate) Mutation() *OrganizationAllowedGroupMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *OrganizationAllowedGroupUpdate) ClearOrganization() *OrganizationAllowedGroupUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *OrganizationAllowedGroupUpdate) ClearGroup() *OrganizationAllowedGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrganizationAllowedGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationAllowedGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrganizationAllowedGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationAllowedGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationAllowedGroupUpdate) check() error {
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationAllowedGroup.organization"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationAllowedGroup.group"`)
	}
	return nil
}

func (_u *OrganizationAllowedGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationallowedgroup.Table, organizationallowedgroup.Columns, sqlgraph.NewFieldSpec(organizationallowedgroup.FieldOrganizationID, field.TypeInt64), sqlgraph.NewFieldSpec(organizationallowedgroup.FieldGroupID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationallowedgroup.OrganizationTable,
			Columns: []string{organizationallowedgroup.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationallowedgroup.OrganizationTable,
			Columns: []string{organizationallowedgroup.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationallowedgroup.GroupTable,
			Columns: []string{organizationallowedgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationallowedgroup.GroupTable,
			Columns: []string{organizationallowedgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationallowedgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrganizationAllowedGroupUpdateOne is the builder for updating a single OrganizationAllowedGroup entity.
type OrganizationAllowedGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationAllowedGroupMutation
}

// SetOrganizationID sets the "organization_id" field.
func (_u *OrganizationAllowedGroupUpdateOne) SetOrganizationID(v int64) *OrganizationAllowedGroupUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *OrganizationAllowedGroupUpdateOne) SetNillableOrganizationID(v *int64) *OrganizationAllowedGroupUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OrganizationAllowedGroupUpdateOne) SetGroupID(v int64) *OrganizationAllowedGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OrganizationAllowedGroupUpdateOne) SetNillableGroupID(v *int64) *OrganizationAllowedGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *OrganizationAllowedGroupUpdateOne) SetOrganization(v *Organization) *OrganizationAllowedGroupUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *OrganizationAllowedGroupUpdateOne) SetGroup(v *Group) *OrganizationAllowedGroupUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the OrganizationAllowedGroupMutation object of the builder.
func (_u *OrganizationAllowedGroupUpdateOne) Mutation() *OrganizationAllowedGroupMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *OrganizationAllowedGroupUpdateOne) ClearOrganization() *OrganizationAllowedGroupUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *OrganizationAllowedGroupUpdateOne) ClearGroup() *OrganizationAllowedGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the OrganizationAllowedGroupUpdate builder.
func (_u *OrganizationAllowedGroupUpdateOne) Where(ps ...predicate.OrganizationAllowedGroup) *OrganizationAllowedGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrganizationAllowedGroupUpdateOne) Select(field string, fields ...string) *OrganizationAllowedGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrganizationAllowedGroup entity.
func (_u *OrganizationAllowedGroupUpdateOne) Save(ctx context.Context) (*OrganizationAllowedGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationAllowedGroupUpdateOne) SaveX(ctx context.Context) *OrganizationAllowedGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrganizationAllowedGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationAllowedGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationAllowedGroupUpdateOne) check() error {
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationAllowedGroup.organization"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationAllowedGroup.group"`)
	}
	return nil
}

func (_u *OrganizationAllowedGroupUpdateOne) sqlSave(ctx context.Context) (_node *OrganizationAllowedGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationallowedgroup.Table, organizationallowedgroup.Columns, sqlgraph.NewFieldSpec(organizationallowedgroup.FieldOrganizationID, field.TypeInt64), sqlgraph.NewFieldSpec(organizationallowedgroup.FieldGroupID, field.TypeInt64))
	if id, ok := _u.mutation.OrganizationID(); !ok {
		return nil, &ValidationError{Name: "organization_id", err: errors.New(`ent: missing "OrganizationAllowedGroup.organization_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "OrganizationAllowedGroup.group_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !organizationallowedgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationallowedgroup.OrganizationTable,
			Columns: []string{organizationallowedgroup.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationallowedgroup.OrganizationTable,
			Columns: []string{organizationallowedgroup.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationallowedgroup.GroupTable,
			Columns: []string{organizationallowedgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationallowedgroup.GroupTable,
			Columns: []string{organizationallowedgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrganizationAllowedGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationallowedgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
