// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/organizationmember"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OrganizationMemberCreate is the builder for creating a OrganizationMember entity.
type OrganizationMemberCreate struct {
	config
	mutation *OrganizationMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrganizationMemberCreate) SetCreatedAt(v time.Time) *OrganizationMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrganizationMemberCreate) SetNillableCreatedAt(v *time.Time) *OrganizationMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrganizationMemberCreate) SetUpdatedAt(v time.Time) *OrganizationMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrganizationMemberCreate) SetNillableUpdatedAt(v *time.Time) *OrganizationMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *OrganizationMemberCreate) SetOrganizationID(v int64) *OrganizationMemberCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OrganizationMemberCreate) SetUserID(v int64) *OrganizationMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *OrganizationMemberCreate) SetOrganization(v *Organization) *OrganizationMemberCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *OrganizationMemberCreate) SetUser(v *User) *OrganizationMemberCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the OrganizationMemberMutation object of the builder.
func (_c *OrganizationMemberCreate) Mutation() *OrganizationMemberMutation {
	return _c.mutation
}

// Save creates the OrganizationMember in the database.
func (_c *OrganizationMemberCreate) Save(ctx context.Context) (*OrganizationMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrganizationMemberCreate) SaveX(ctx context.Context) *OrganizationMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrganizationMemberCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := organizationmember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := organizationmember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrganizationMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrganizationMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrganizationMember.updated_at"`)}
	}
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "OrganizationMember.organization_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OrganizationMember.user_id"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "OrganizationMember.organization"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OrganizationMember.user"`)}
	}
	return nil
}

func (_c *OrganizationMemberCreate) sqlSave(ctx context.Context) (*OrganizationMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrganizationMemberCreate) createSpec() (*OrganizationMember, *sqlgraph.CreateSpec) {
	var (
		_node = &OrganizationMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(organizationmember.Table, sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(organizationmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationmember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organizationmember.OrganizationTable,
			Columns: []string{organizationmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   organizationmember.UserTable,
			Columns: []string{organizationmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrganizationMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrganizationMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrganizationMemberCreate) OnConflict(opts ...sql.ConflictOption) *OrganizationMemberUpsertOne {
	_c.conflict = opts
	return &OrganizationMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrganizationMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrganizationMemberCreate) OnConflictColumns(columns ...string) *OrganizationMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrganizationMemberUpsertOne{
		create: _c,
	}
}

type (
	// OrganizationMemberUpsertOne is the builder for "upsert"-ing
	//  one OrganizationMember node.
	OrganizationMemberUpsertOne struct {
		create *OrganizationMemberCreate
	}

	// OrganizationMemberUpsert is the "OnConflict" setter.
	OrganizationMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationMemberUpsert) SetUpdatedAt(v time.Time) *OrganizationMemberUpsert {
	u.Set(organizationmember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationMemberUpsert) UpdateUpdatedAt() *OrganizationMemberUpsert {
	u.SetExcluded(organizationmember.FieldUpdatedAt)
	return u
}

// SetOrganizationID sets the "organization_id" field.
func (u *OrganizationMemberUpsert) SetOrganizationID(v int64) *OrganizationMemberUpsert {
	u.Set(organizationmember.FieldOrganizationID, v)
	return u
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *OrganizationMemberUpsert) UpdateOrganizationID() *OrganizationMemberUpsert {
	u.SetExcluded(organizationmember.FieldOrganizationID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OrganizationMemberUpsert) SetUserID(v int64) *OrganizationMemberUpsert {
	u.Set(organizationmember.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrganizationMemberUpsert) UpdateUserID() *OrganizationMemberUpsert {
	u.SetExcluded(organizationmember.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OrganizationMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrganizationMemberUpsertOne) UpdateNewValues() *OrganizationMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(organizationmember.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrganizationMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrganizationMemberUpsertOne) Ignore() *OrganizationMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrganizationMemberUpsertOne) DoNothing() *OrganizationMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrganizationMemberCreate.OnConflict
// documentation for more info.
func (u *OrganizationMemberUpsertOne) Update(set func(*OrganizationMemberUpsert)) *OrganizationMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrganizationMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationMemberUpsertOne) SetUpdatedAt(v time.Time) *OrganizationMemberUpsertOne {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationMemberUpsertOne) UpdateUpdatedAt() *OrganizationMemberUpsertOne {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrganizationID sets the "organization_id" field.
func (u *OrganizationMemberUpsertOne) SetOrganizationID(v int64) *OrganizationMemberUpsertOne {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.SetOrganizationID(v)
	})
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *OrganizationMemberUpsertOne) UpdateOrganizationID() *OrganizationMemberUpsertOne {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.UpdateOrganizationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrganizationMemberUpsertOne) SetUserID(v int64) *OrganizationMemberUpsertOne {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrganizationMemberUpsertOne) UpdateUserID() *OrganizationMemberUpsertOne {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *OrganizationMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrganizationMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrganizationMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrganizationMemberUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrganizationMemberUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrganizationMemberCreateBulk is the builder for creating many OrganizationMember entities in bulk.
type OrganizationMemberCreateBulk struct {
	config
	err      error
	builders []*OrganizationMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the OrganizationMember entities in the database.
func (_c *OrganizationMemberCreateBulk) Save(ctx context.Context) ([]*OrganizationMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrganizationMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrganizationMemberCreateBulk) SaveX(ctx context.Context) []*OrganizationMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrganizationMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrganizationMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrganizationMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrganizationMemberUpsertBulk {
	_c.conflict = opts
	return &OrganizationMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrganizationMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrganizationMemberCreateBulk) OnConflictColumns(columns ...string) *OrganizationMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrganizationMemberUpsertBulk{
		create: _c,
	}
}

// OrganizationMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of OrganizationMember nodes.
type OrganizationMemberUpsertBulk struct {
	create *OrganizationMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OrganizationMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrganizationMemberUpsertBulk) UpdateNewValues() *OrganizationMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(organizationmember.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrganizationMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrganizationMemberUpsertBulk) Ignore() *OrganizationMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrganizationMemberUpsertBulk) DoNothing() *OrganizationMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrganizationMemberCreateBulk.OnConflict
// documentation for more info.
func (u *OrganizationMemberUpsertBulk) Update(set func(*OrganizationMemberUpsert)) *OrganizationMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrganizationMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationMemberUpsertBulk) SetUpdatedAt(v time.Time) *OrganizationMemberUpsertBulk {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationMemberUpsertBulk) UpdateUpdatedAt() *OrganizationMemberUpsertBulk {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrganizationID sets the "organization_id" field.
func (u *OrganizationMemberUpsertBulk) SetOrganizationID(v int64) *OrganizationMemberUpsertBulk {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.SetOrganizationID(v)
	})
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *OrganizationMemberUpsertBulk) UpdateOrganizationID() *OrganizationMemberUpsertBulk {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.UpdateOrganizationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrganizationMemberUpsertBulk) SetUserID(v int64) *OrganizationMemberUpsertBulk {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrganizationMemberUpsertBulk) UpdateUserID() *OrganizationMemberUpsertBulk {
	return u.Update(func(s *OrganizationMemberUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *OrganizationMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrganizationMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrganizationMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrganizationMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
