// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// Organization is the model entity for the Organization schema.
type Organization struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// RestrictPublicGroups holds the value of the "restrict_public_groups" field.
	RestrictPublicGroups bool `json:"restrict_public_groups,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrganizationQuery when eager-loading is set.
	Edges        OrganizationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrganizationEdges holds the relations/edges for other nodes in the graph.
type OrganizationEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Members holds the value of the members edge.
	Members []*OrganizationMember `json:"members,omitempty"`
	// Invitations holds the value of the invitations edge.
	Invitations []*RedeemCode `json:"invitations,omitempty"`
	// AllowedGroups holds the value of the allowed_groups edge.
	AllowedGroups []*Group `json:"allowed_groups,omitempty"`
	// OrganizationAllowedGroups holds the value of the organization_allowed_groups edge.
	OrganizationAllowedGroups []*OrganizationAllowedGroup `json:"organization_allowed_groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) MembersOrErr() ([]*OrganizationMember, error) {
	if e.loadedTypes[1] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// InvitationsOrErr returns the Invitations value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) InvitationsOrErr() ([]*RedeemCode, error) {
	if e.loadedTypes[2] {
		return e.Invitations, nil
	}
	return nil, &NotLoadedError{edge: "invitations"}
}

// AllowedGroupsOrErr returns the AllowedGroups value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) AllowedGroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[3] {
		return e.AllowedGroups, nil
	}
	return nil, &NotLoadedError{edge: "allowed_groups"}
}

// OrganizationAllowedGroupsOrErr returns the OrganizationAllowedGroups value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) OrganizationAllowedGroupsOrErr() ([]*OrganizationAllowedGroup, error) {
	if e.loadedTypes[4] {
		return e.OrganizationAllowedGroups, nil
	}
	return nil, &NotLoadedError{edge: "organization_allowed_groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Organization) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case organization.FieldRestrictPublicGroups:
			values[i] = new(sql.NullBool)
		case organization.FieldID, organization.FieldOwnerUserID:
			values[i] = new(sql.NullInt64)
		case organization.FieldName, organization.FieldStatus:
			values[i] = new(sql.NullString)
		case organization.FieldCreatedAt, organization.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Organization fields.
func (_m *Organization) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case organization.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case organization.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case organization.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case organization.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case organization.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case organization.FieldRestrictPublicGroups:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field restrict_public_groups", values[i])
			} else if value.Valid {
				_m.RestrictPublicGroups = value.Bool
			}
		case organization.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Organization.
// This includes values selected through modifiers, order, etc.
func (_m *Organization) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Organization entity.
func (_m *Organization) QueryOwner() *UserQuery {
	return NewOrganizationClient(_m.config).QueryOwner(_m)
}

// QueryMembers queries the "members" edge of the Organization entity.
func (_m *Organization) QueryMembers() *OrganizationMemberQuery {
	return NewOrganizationClient(_m.config).QueryMembers(_m)
}

// QueryInvitations queries the "invitations" edge of the Organization entity.
func (_m *Organization) QueryInvitations() *RedeemCodeQuery {
	return NewOrganizationClient(_m.config).QueryInvitations(_m)
}

// QueryAllowedGroups queries the "allowed_groups" edge of the Organization entity.
func (_m *Organization) QueryAllowedGroups() *GroupQuery {
	return NewOrganizationClient(_m.config).QueryAllowedGroups(_m)
}

// QueryOrganizationAllowedGroups queries the "organization_allowed_groups" edge of the Organization entity.
func (_m *Organization) QueryOrganizationAllowedGroups() *OrganizationAllowedGroupQuery {
	return NewOrganizationClient(_m.config).QueryOrganizationAllowedGroups(_m)
}

// Update returns a builder for updating this Organization.
// Note that you need to call Organization.Unwrap() before calling this method if this Organization
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Organization) Update() *OrganizationUpdateOne {
	return NewOrganizationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Organization entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Organization) Unwrap() *Organization {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Organization is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Organization) String() string {
	var builder strings.Builder
	builder.WriteString("Organization(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("restrict_public_groups=")
	builder.WriteString(fmt.Sprintf("%v", _m.RestrictPublicGroups))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// Organizations is a parsable slice of Organization.
type Organizations []*Organization
