// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/organizationquotarequest"
)

// OrganizationQuotaRequestCreate is the builder for creating a OrganizationQuotaRequest entity.
type OrganizationQuotaRequestCreate struct {
	config
	mutation *OrganizationQuotaRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrganizationQuotaRequestCreate) SetCreatedAt(v time.Time) *OrganizationQuotaRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableCreatedAt(v *time.Time) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrganizationQuotaRequestCreate) SetUpdatedAt(v time.Time) *OrganizationQuotaRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableUpdatedAt(v *time.Time) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *OrganizationQuotaRequestCreate) SetOrganizationID(v int64) *OrganizationQuotaRequestCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OrganizationQuotaRequestCreate) SetUserID(v int64) *OrganizationQuotaRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *OrganizationQuotaRequestCreate) SetAmount(v float64) *OrganizationQuotaRequestCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *OrganizationQuotaRequestCreate) SetReason(v string) *OrganizationQuotaRequestCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableReason(v *string) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrganizationQuotaRequestCreate) SetStatus(v string) *OrganizationQuotaRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableStatus(v *string) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGrantSource sets the "grant_source" field.
func (_c *OrganizationQuotaRequestCreate) SetGrantSource(v string) *OrganizationQuotaRequestCreate {
	_c.mutation.SetGrantSource(v)
	return _c
}

// SetNillableGrantSource sets the "grant_source" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableGrantSource(v *string) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetGrantSource(*v)
	}
	return _c
}

// SetGrantedAmount sets the "granted_amount" field.
func (_c *OrganizationQuotaRequestCreate) SetGrantedAmount(v float64) *OrganizationQuotaRequestCreate {
	_c.mutation.SetGrantedAmount(v)
	return _c
}

// SetNillableGrantedAmount sets the "granted_amount" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableGrantedAmount(v *float64) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetGrantedAmount(*v)
	}
	return _c
}

// SetSnapshotMode sets the "snapshot_mode" field.
func (_c *OrganizationQuotaRequestCreate) SetSnapshotMode(v string) *OrganizationQuotaRequestCreate {
	_c.mutation.SetSnapshotMode(v)
	return _c
}

// SetNillableSnapshotMode sets the "snapshot_mode" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableSnapshotMode(v *string) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetSnapshotMode(*v)
	}
	return _c
}

// SetSnapshotLimit sets the "snapshot_limit" field.
func (_c *OrganizationQuotaRequestCreate) SetSnapshotLimit(v float64) *OrganizationQuotaRequestCreate {
	_c.mutation.SetSnapshotLimit(v)
	return _c
}

// SetNillableSnapshotLimit sets the "snapshot_limit" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableSnapshotLimit(v *float64) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetSnapshotLimit(*v)
	}
	return _c
}

// SetSnapshotUsed sets the "snapshot_used" field.
func (_c *OrganizationQuotaRequestCreate) SetSnapshotUsed(v float64) *OrganizationQuotaRequestCreate {
	_c.mutation.SetSnapshotUsed(v)
	return _c
}

// SetNillableSnapshotUsed sets the "snapshot_used" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableSnapshotUsed(v *float64) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetSnapshotUsed(*v)
	}
	return _c
}

// SetReviewerUserID sets the "reviewer_user_id" field.
func (_c *OrganizationQuotaRequestCreate) SetReviewerUserID(v int64) *OrganizationQuotaRequestCreate {
	_c.mutation.SetReviewerUserID(v)
	return _c
}

// SetNillableReviewerUserID sets the "reviewer_user_id" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableReviewerUserID(v *int64) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetReviewerUserID(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *OrganizationQuotaRequestCreate) SetReviewedAt(v time.Time) *OrganizationQuotaRequestCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableReviewedAt(v *time.Time) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetReviewNote sets the "review_note" field.
func (_c *OrganizationQuotaRequestCreate) SetReviewNote(v string) *OrganizationQuotaRequestCreate {
	_c.mutation.SetReviewNote(v)
	return _c
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_c *OrganizationQuotaRequestCreate) SetNillableReviewNote(v *string) *OrganizationQuotaRequestCreate {
	if v != nil {
		_c.SetReviewNote(*v)
	}
	return _c
}

// Mutation returns the OrganizationQuotaRequestMutation object of the builder.
func (_c *OrganizationQuotaRequestCreate) Mutation() *OrganizationQuotaRequestMutation {
	return _c.mutation
}

// Save creates the OrganizationQuotaRequest in the database.
func (_c *OrganizationQuotaRequestCreate) Save(ctx context.Context) (*OrganizationQuotaRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrganizationQuotaRequestCreate) SaveX(ctx context.Context) *OrganizationQuotaRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationQuotaRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationQuotaRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrganizationQuotaRequestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := organizationquotarequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := organizationquotarequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := organizationquotarequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SnapshotMode(); !ok {
		v := organizationquotarequest.DefaultSnapshotMode
		_c.mutation.SetSnapshotMode(v)
	}
	if _, ok := _c.mutation.SnapshotUsed(); !ok {
		v := organizationquotarequest.DefaultSnapshotUsed
		_c.mutation.SetSnapshotUsed(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrganizationQuotaRequestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrganizationQuotaRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrganizationQuotaRequest.updated_at"`)}
	}
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "OrganizationQuotaRequest.organization_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OrganizationQuotaRequest.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "OrganizationQuotaRequest.amount"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := organizationquotarequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OrganizationQuotaRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := organizationquotarequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.GrantSource(); ok {
		if err := organizationquotarequest.GrantSourceValidator(v); err != nil {
			return &ValidationError{Name: "grant_source", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.grant_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SnapshotMode(); !ok {
		return &ValidationError{Name: "snapshot_mode", err: errors.New(`ent: missing required field "OrganizationQuotaRequest.snapshot_mode"`)}
	}
	if v, ok := _c.mutation.SnapshotMode(); ok {
		if err := organizationquotarequest.SnapshotModeValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_mode", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.snapshot_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SnapshotUsed(); !ok {
		return &ValidationError{Name: "snapshot_used", err: errors.New(`ent: missing required field "OrganizationQuotaRequest.snapshot_used"`)}
	}
	if v, ok := _c.mutation.ReviewNote(); ok {
		if err := organizationquotarequest.ReviewNoteValidator(v); err != nil {
			return &ValidationError{Name: "review_note", err: fmt.Errorf(`ent: validator failed for field "OrganizationQuotaRequest.review_note": %w`, err)}
		}
	}
	return nil
}

func (_c *OrganizationQuotaRequestCreate) sqlSave(ctx context.Context) (*OrganizationQuotaRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrganizationQuotaRequestCreate) createSpec() (*OrganizationQuotaRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &OrganizationQuotaRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(organizationquotarequest.Table, sqlgraph.NewFieldSpec(organizationquotarequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(organizationquotarequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationquotarequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OrganizationID(); ok {
		_spec.SetField(organizationquotarequest.FieldOrganizationID, field.TypeInt64, value)
		_node.OrganizationID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(organizationquotarequest.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(organizationquotarequest.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(organizationquotarequest.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(organizationquotarequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.GrantSource(); ok {
		_spec.SetField(organizationquotarequest.FieldGrantSource, field.TypeString, value)
		_node.GrantSource = &value
	}
	if value, ok := _c.mutation.GrantedAmount(); ok {
		_spec.SetField(organizationquotarequest.FieldGrantedAmount, field.TypeFloat64, value)
		_node.GrantedAmount = &value
	}
	if value, ok := _c.mutation.SnapshotMode(); ok {
		_spec.SetField(organizationquotarequest.FieldSnapshotMode, field.TypeString, value)
		_node.SnapshotMode = value
	}
	if value, ok := _c.mutation.SnapshotLimit(); ok {
		_spec.SetField(organizationquotarequest.FieldSnapshotLimit, field.TypeFloat64, value)
		_node.SnapshotLimit = &value
	}
	if value, ok := _c.mutation.SnapshotUsed(); ok {
		_spec.SetField(organizationquotarequest.FieldSnapshotUsed, field.TypeFloat64, value)
		_node.SnapshotUsed = value
	}
	if value, ok := _c.mutation.ReviewerUserID(); ok {
		_spec.SetField(organizationquotarequest.FieldReviewerUserID, field.TypeInt64, value)
		_node.ReviewerUserID = &value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(organizationquotarequest.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.ReviewNote(); ok {
		_spec.SetField(organizationquotarequest.FieldReviewNote, field.TypeString, value)
		_node.ReviewNote = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrganizationQuotaRequest.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrganizationQuotaRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrganizationQuotaRequestCreate) OnConflict(opts ...sql.ConflictOption) *OrganizationQuotaRequestUpsertOne {
	_c.conflict = opts
	return &OrganizationQuotaRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrganizationQuotaRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrganizationQuotaRequestCreate) OnConflictColumns(columns ...string) *OrganizationQuotaRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrganizationQuotaRequestUpsertOne{
		create: _c,
	}
}

type (
	// OrganizationQuotaRequestUpsertOne is the builder for "upsert"-ing
	//  one OrganizationQuotaRequest node.
	OrganizationQuotaRequestUpsertOne struct {
		create *OrganizationQuotaRequestCreate
	}

	// OrganizationQuotaRequestUpsert is the "OnConflict" setter.
	OrganizationQuotaRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationQuotaRequestUpsert) SetUpdatedAt(v time.Time) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateUpdatedAt() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldUpdatedAt)
	return u
}

// SetOrganizationID sets the "organization_id" field.
func (u *OrganizationQuotaRequestUpsert) SetOrganizationID(v int64) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldOrganizationID, v)
	return u
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateOrganizationID() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldOrganizationID)
	return u
}

// AddOrganizationID adds v to the "organization_id" field.
func (u *OrganizationQuotaRequestUpsert) AddOrganizationID(v int64) *OrganizationQuotaRequestUpsert {
	u.Add(organizationquotarequest.FieldOrganizationID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OrganizationQuotaRequestUpsert) SetUserID(v int64) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateUserID() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *OrganizationQuotaRequestUpsert) AddUserID(v int64) *OrganizationQuotaRequestUpsert {
	u.Add(organizationquotarequest.FieldUserID, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *OrganizationQuotaRequestUpsert) SetAmount(v float64) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateAmount() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *OrganizationQuotaRequestUpsert) AddAmount(v float64) *OrganizationQuotaRequestUpsert {
	u.Add(organizationquotarequest.FieldAmount, v)
	return u
}

// SetReason sets the "reason" field.
func (u *OrganizationQuotaRequestUpsert) SetReason(v string) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateReason() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *OrganizationQuotaRequestUpsert) ClearReason() *OrganizationQuotaRequestUpsert {
	u.SetNull(organizationquotarequest.FieldReason)
	return u
}

// SetStatus sets the "status" field.
func (u *OrganizationQuotaRequestUpsert) SetStatus(v string) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateStatus() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldStatus)
	return u
}

// SetGrantSource sets the "grant_source" field.
func (u *OrganizationQuotaRequestUpsert) SetGrantSource(v string) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldGrantSource, v)
	return u
}

// UpdateGrantSource sets the "grant_source" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateGrantSource() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldGrantSource)
	return u
}

// ClearGrantSource clears the value of the "grant_source" field.
func (u *OrganizationQuotaRequestUpsert) ClearGrantSource() *OrganizationQuotaRequestUpsert {
	u.SetNull(organizationquotarequest.FieldGrantSource)
	return u
}

// SetGrantedAmount sets the "granted_amount" field.
func (u *OrganizationQuotaRequestUpsert) SetGrantedAmount(v float64) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldGrantedAmount, v)
	return u
}

// UpdateGrantedAmount sets the "granted_amount" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateGrantedAmount() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldGrantedAmount)
	return u
}

// AddGrantedAmount adds v to the "granted_amount" field.
func (u *OrganizationQuotaRequestUpsert) AddGrantedAmount(v float64) *OrganizationQuotaRequestUpsert {
	u.Add(organizationquotarequest.FieldGrantedAmount, v)
	return u
}

// ClearGrantedAmount clears the value of the "granted_amount" field.
func (u *OrganizationQuotaRequestUpsert) ClearGrantedAmount() *OrganizationQuotaRequestUpsert {
	u.SetNull(organizationquotarequest.FieldGrantedAmount)
	return u
}

// SetSnapshotMode sets the "snapshot_mode" field.
func (u *OrganizationQuotaRequestUpsert) SetSnapshotMode(v string) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldSnapshotMode, v)
	return u
}

// UpdateSnapshotMode sets the "snapshot_mode" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateSnapshotMode() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldSnapshotMode)
	return u
}

// SetSnapshotLimit sets the "snapshot_limit" field.
func (u *OrganizationQuotaRequestUpsert) SetSnapshotLimit(v float64) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldSnapshotLimit, v)
	return u
}

// UpdateSnapshotLimit sets the "snapshot_limit" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateSnapshotLimit() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldSnapshotLimit)
	return u
}

// AddSnapshotLimit adds v to the "snapshot_limit" field.
func (u *OrganizationQuotaRequestUpsert) AddSnapshotLimit(v float64) *OrganizationQuotaRequestUpsert {
	u.Add(organizationquotarequest.FieldSnapshotLimit, v)
	return u
}

// ClearSnapshotLimit clears the value of the "snapshot_limit" field.
func (u *OrganizationQuotaRequestUpsert) ClearSnapshotLimit() *OrganizationQuotaRequestUpsert {
	u.SetNull(organizationquotarequest.FieldSnapshotLimit)
	return u
}

// SetSnapshotUsed sets the "snapshot_used" field.
func (u *OrganizationQuotaRequestUpsert) SetSnapshotUsed(v float64) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldSnapshotUsed, v)
	return u
}

// UpdateSnapshotUsed sets the "snapshot_used" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateSnapshotUsed() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldSnapshotUsed)
	return u
}

// AddSnapshotUsed adds v to the "snapshot_used" field.
func (u *OrganizationQuotaRequestUpsert) AddSnapshotUsed(v float64) *OrganizationQuotaRequestUpsert {
	u.Add(organizationquotarequest.FieldSnapshotUsed, v)
	return u
}

// SetReviewerUserID sets the "reviewer_user_id" field.
func (u *OrganizationQuotaRequestUpsert) SetReviewerUserID(v int64) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldReviewerUserID, v)
	return u
}

// UpdateReviewerUserID sets the "reviewer_user_id" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateReviewerUserID() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldReviewerUserID)
	return u
}

// AddReviewerUserID adds v to the "reviewer_user_id" field.
func (u *OrganizationQuotaRequestUpsert) AddReviewerUserID(v int64) *OrganizationQuotaRequestUpsert {
	u.Add(organizationquotarequest.FieldReviewerUserID, v)
	return u
}

// ClearReviewerUserID clears the value of the "reviewer_user_id" field.
func (u *OrganizationQuotaRequestUpsert) ClearReviewerUserID() *OrganizationQuotaRequestUpsert {
	u.SetNull(organizationquotarequest.FieldReviewerUserID)
	return u
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *OrganizationQuotaRequestUpsert) SetReviewedAt(v time.Time) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldReviewedAt, v)
	return u
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateReviewedAt() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldReviewedAt)
	return u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *OrganizationQuotaRequestUpsert) ClearReviewedAt() *OrganizationQuotaRequestUpsert {
	u.SetNull(organizationquotarequest.FieldReviewedAt)
	return u
}

// SetReviewNote sets the "review_note" field.
func (u *OrganizationQuotaRequestUpsert) SetReviewNote(v string) *OrganizationQuotaRequestUpsert {
	u.Set(organizationquotarequest.FieldReviewNote, v)
	return u
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsert) UpdateReviewNote() *OrganizationQuotaRequestUpsert {
	u.SetExcluded(organizationquotarequest.FieldReviewNote)
	return u
}

// ClearReviewNote clears the value of the "review_note" field.
func (u *OrganizationQuotaRequestUpsert) ClearReviewNote() *OrganizationQuotaRequestUpsert {
	u.SetNull(organizationquotarequest.FieldReviewNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OrganizationQuotaRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrganizationQuotaRequestUpsertOne) UpdateNewValues() *OrganizationQuotaRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(organizationquotarequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrganizationQuotaRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrganizationQuotaRequestUpsertOne) Ignore() *OrganizationQuotaRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrganizationQuotaRequestUpsertOne) DoNothing() *OrganizationQuotaRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrganizationQuotaRequestCreate.OnConflict
// documentation for more info.
func (u *OrganizationQuotaRequestUpsertOne) Update(set func(*OrganizationQuotaRequestUpsert)) *OrganizationQuotaRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrganizationQuotaRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationQuotaRequestUpsertOne) SetUpdatedAt(v time.Time) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateUpdatedAt() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrganizationID sets the "organization_id" field.
func (u *OrganizationQuotaRequestUpsertOne) SetOrganizationID(v int64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetOrganizationID(v)
	})
}

// AddOrganizationID adds v to the "organization_id" field.
func (u *OrganizationQuotaRequestUpsertOne) AddOrganizationID(v int64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddOrganizationID(v)
	})
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateOrganizationID() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateOrganizationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrganizationQuotaRequestUpsertOne) SetUserID(v int64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OrganizationQuotaRequestUpsertOne) AddUserID(v int64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateUserID() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *OrganizationQuotaRequestUpsertOne) SetAmount(v float64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *OrganizationQuotaRequestUpsertOne) AddAmount(v float64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateAmount() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetReason sets the "reason" field.
func (u *OrganizationQuotaRequestUpsertOne) SetReason(v string) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateReason() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *OrganizationQuotaRequestUpsertOne) ClearReason() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearReason()
	})
}

// SetStatus sets the "status" field.
func (u *OrganizationQuotaRequestUpsertOne) SetStatus(v string) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateStatus() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetGrantSource sets the "grant_source" field.
func (u *OrganizationQuotaRequestUpsertOne) SetGrantSource(v string) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetGrantSource(v)
	})
}

// UpdateGrantSource sets the "grant_source" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateGrantSource() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateGrantSource()
	})
}

// ClearGrantSource clears the value of the "grant_source" field.
func (u *OrganizationQuotaRequestUpsertOne) ClearGrantSource() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearGrantSource()
	})
}

// SetGrantedAmount sets the "granted_amount" field.
func (u *OrganizationQuotaRequestUpsertOne) SetGrantedAmount(v float64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetGrantedAmount(v)
	})
}

// AddGrantedAmount adds v to the "granted_amount" field.
func (u *OrganizationQuotaRequestUpsertOne) AddGrantedAmount(v float64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddGrantedAmount(v)
	})
}

// UpdateGrantedAmount sets the "granted_amount" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateGrantedAmount() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateGrantedAmount()
	})
}

// ClearGrantedAmount clears the value of the "granted_amount" field.
func (u *OrganizationQuotaRequestUpsertOne) ClearGrantedAmount() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearGrantedAmount()
	})
}

// SetSnapshotMode sets the "snapshot_mode" field.
func (u *OrganizationQuotaRequestUpsertOne) SetSnapshotMode(v string) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetSnapshotMode(v)
	})
}

// UpdateSnapshotMode sets the "snapshot_mode" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateSnapshotMode() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateSnapshotMode()
	})
}

// SetSnapshotLimit sets the "snapshot_limit" field.
func (u *OrganizationQuotaRequestUpsertOne) SetSnapshotLimit(v float64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetSnapshotLimit(v)
	})
}

// AddSnapshotLimit adds v to the "snapshot_limit" field.
func (u *OrganizationQuotaRequestUpsertOne) AddSnapshotLimit(v float64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddSnapshotLimit(v)
	})
}

// UpdateSnapshotLimit sets the "snapshot_limit" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateSnapshotLimit() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateSnapshotLimit()
	})
}

// ClearSnapshotLimit clears the value of the "snapshot_limit" field.
func (u *OrganizationQuotaRequestUpsertOne) ClearSnapshotLimit() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearSnapshotLimit()
	})
}

// SetSnapshotUsed sets the "snapshot_used" field.
func (u *OrganizationQuotaRequestUpsertOne) SetSnapshotUsed(v float64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetSnapshotUsed(v)
	})
}

// AddSnapshotUsed adds v to the "snapshot_used" field.
func (u *OrganizationQuotaRequestUpsertOne) AddSnapshotUsed(v float64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddSnapshotUsed(v)
	})
}

// UpdateSnapshotUsed sets the "snapshot_used" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateSnapshotUsed() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateSnapshotUsed()
	})
}

// SetReviewerUserID sets the "reviewer_user_id" field.
func (u *OrganizationQuotaRequestUpsertOne) SetReviewerUserID(v int64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetReviewerUserID(v)
	})
}

// AddReviewerUserID adds v to the "reviewer_user_id" field.
func (u *OrganizationQuotaRequestUpsertOne) AddReviewerUserID(v int64) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddReviewerUserID(v)
	})
}

// UpdateReviewerUserID sets the "reviewer_user_id" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateReviewerUserID() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateReviewerUserID()
	})
}

// ClearReviewerUserID clears the value of the "reviewer_user_id" field.
func (u *OrganizationQuotaRequestUpsertOne) ClearReviewerUserID() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearReviewerUserID()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *OrganizationQuotaRequestUpsertOne) SetReviewedAt(v time.Time) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateReviewedAt() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *OrganizationQuotaRequestUpsertOne) ClearReviewedAt() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearReviewedAt()
	})
}

// SetReviewNote sets the "review_note" field.
func (u *OrganizationQuotaRequestUpsertOne) SetReviewNote(v string) *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetReviewNote(v)
	})
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertOne) UpdateReviewNote() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateReviewNote()
	})
}

// ClearReviewNote clears the value of the "review_note" field.
func (u *OrganizationQuotaRequestUpsertOne) ClearReviewNote() *OrganizationQuotaRequestUpsertOne {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearReviewNote()
	})
}

// Exec executes the query.
func (u *OrganizationQuotaRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrganizationQuotaRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrganizationQuotaRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrganizationQuotaRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrganizationQuotaRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrganizationQuotaRequestCreateBulk is the builder for creating many OrganizationQuotaRequest entities in bulk.
type OrganizationQuotaRequestCreateBulk struct {
	config
	err      error
	builders []*OrganizationQuotaRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the OrganizationQuotaRequest entities in the database.
func (_c *OrganizationQuotaRequestCreateBulk) Save(ctx context.Context) ([]*OrganizationQuotaRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrganizationQuotaRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationQuotaRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrganizationQuotaRequestCreateBulk) SaveX(ctx context.Context) []*OrganizationQuotaRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationQuotaRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationQuotaRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrganizationQuotaRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrganizationQuotaRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrganizationQuotaRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrganizationQuotaRequestUpsertBulk {
	_c.conflict = opts
	return &OrganizationQuotaRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrganizationQuotaRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrganizationQuotaRequestCreateBulk) OnConflictColumns(columns ...string) *OrganizationQuotaRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrganizationQuotaRequestUpsertBulk{
		create: _c,
	}
}

// OrganizationQuotaRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of OrganizationQuotaRequest nodes.
type OrganizationQuotaRequestUpsertBulk struct {
	create *OrganizationQuotaRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OrganizationQuotaRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrganizationQuotaRequestUpsertBulk) UpdateNewValues() *OrganizationQuotaRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(organizationquotarequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrganizationQuotaRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrganizationQuotaRequestUpsertBulk) Ignore() *OrganizationQuotaRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrganizationQuotaRequestUpsertBulk) DoNothing() *OrganizationQuotaRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrganizationQuotaRequestCreateBulk.OnConflict
// documentation for more info.
func (u *OrganizationQuotaRequestUpsertBulk) Update(set func(*OrganizationQuotaRequestUpsert)) *OrganizationQuotaRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrganizationQuotaRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetUpdatedAt(v time.Time) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateUpdatedAt() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrganizationID sets the "organization_id" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetOrganizationID(v int64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetOrganizationID(v)
	})
}

// AddOrganizationID adds v to the "organization_id" field.
func (u *OrganizationQuotaRequestUpsertBulk) AddOrganizationID(v int64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddOrganizationID(v)
	})
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateOrganizationID() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateOrganizationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetUserID(v int64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OrganizationQuotaRequestUpsertBulk) AddUserID(v int64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateUserID() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetAmount(v float64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *OrganizationQuotaRequestUpsertBulk) AddAmount(v float64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateAmount() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetReason sets the "reason" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetReason(v string) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateReason() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *OrganizationQuotaRequestUpsertBulk) ClearReason() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearReason()
	})
}

// SetStatus sets the "status" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetStatus(v string) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateStatus() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetGrantSource sets the "grant_source" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetGrantSource(v string) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetGrantSource(v)
	})
}

// UpdateGrantSource sets the "grant_source" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateGrantSource() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateGrantSource()
	})
}

// ClearGrantSource clears the value of the "grant_source" field.
func (u *OrganizationQuotaRequestUpsertBulk) ClearGrantSource() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearGrantSource()
	})
}

// SetGrantedAmount sets the "granted_amount" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetGrantedAmount(v float64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetGrantedAmount(v)
	})
}

// AddGrantedAmount adds v to the "granted_amount" field.
func (u *OrganizationQuotaRequestUpsertBulk) AddGrantedAmount(v float64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddGrantedAmount(v)
	})
}

// UpdateGrantedAmount sets the "granted_amount" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateGrantedAmount() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateGrantedAmount()
	})
}

// ClearGrantedAmount clears the value of the "granted_amount" field.
func (u *OrganizationQuotaRequestUpsertBulk) ClearGrantedAmount() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearGrantedAmount()
	})
}

// SetSnapshotMode sets the "snapshot_mode" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetSnapshotMode(v string) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetSnapshotMode(v)
	})
}

// UpdateSnapshotMode sets the "snapshot_mode" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateSnapshotMode() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateSnapshotMode()
	})
}

// SetSnapshotLimit sets the "snapshot_limit" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetSnapshotLimit(v float64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetSnapshotLimit(v)
	})
}

// AddSnapshotLimit adds v to the "snapshot_limit" field.
func (u *OrganizationQuotaRequestUpsertBulk) AddSnapshotLimit(v float64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddSnapshotLimit(v)
	})
}

// UpdateSnapshotLimit sets the "snapshot_limit" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateSnapshotLimit() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateSnapshotLimit()
	})
}

// ClearSnapshotLimit clears the value of the "snapshot_limit" field.
func (u *OrganizationQuotaRequestUpsertBulk) ClearSnapshotLimit() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearSnapshotLimit()
	})
}

// SetSnapshotUsed sets the "snapshot_used" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetSnapshotUsed(v float64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetSnapshotUsed(v)
	})
}

// AddSnapshotUsed adds v to the "snapshot_used" field.
func (u *OrganizationQuotaRequestUpsertBulk) AddSnapshotUsed(v float64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddSnapshotUsed(v)
	})
}

// UpdateSnapshotUsed sets the "snapshot_used" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateSnapshotUsed() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateSnapshotUsed()
	})
}

// SetReviewerUserID sets the "reviewer_user_id" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetReviewerUserID(v int64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetReviewerUserID(v)
	})
}

// AddReviewerUserID adds v to the "reviewer_user_id" field.
func (u *OrganizationQuotaRequestUpsertBulk) AddReviewerUserID(v int64) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.AddReviewerUserID(v)
	})
}

// UpdateReviewerUserID sets the "reviewer_user_id" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateReviewerUserID() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateReviewerUserID()
	})
}

// ClearReviewerUserID clears the value of the "reviewer_user_id" field.
func (u *OrganizationQuotaRequestUpsertBulk) ClearReviewerUserID() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearReviewerUserID()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetReviewedAt(v time.Time) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateReviewedAt() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *OrganizationQuotaRequestUpsertBulk) ClearReviewedAt() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearReviewedAt()
	})
}

// SetReviewNote sets the "review_note" field.
func (u *OrganizationQuotaRequestUpsertBulk) SetReviewNote(v string) *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.SetReviewNote(v)
	})
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *OrganizationQuotaRequestUpsertBulk) UpdateReviewNote() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.UpdateReviewNote()
	})
}

// ClearReviewNote clears the value of the "review_note" field.
func (u *OrganizationQuotaRequestUpsertBulk) ClearReviewNote() *OrganizationQuotaRequestUpsertBulk {
	return u.Update(func(s *OrganizationQuotaRequestUpsert) {
		s.ClearReviewNote()
	})
}

// Exec executes the query.
func (u *OrganizationQuotaRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrganizationQuotaRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrganizationQuotaRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrganizationQuotaRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
