// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/organizationallowedgroup"
)

// OrganizationAllowedGroupCreate is the builder for creating a OrganizationAllowedGroup entity.
type OrganizationAllowedGroupCreate struct {
	config
	mutation *OrganizationAllowedGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrganizationID sets the "organization_id" field.
func (_c *OrganizationAllowedGroupCreate) SetOrganizationID(v int64) *OrganizationAllowedGroupCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *OrganizationAllowedGroupCreate) SetGroupID(v int64) *OrganizationAllowedGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrganizationAllowedGroupCreate) SetCreatedAt(v time.Time) *OrganizationAllowedGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrganizationAllowedGroupCreate) SetNillableCreatedAt(v *time.Time) *OrganizationAllowedGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *OrganizationAllowedGroupCreate) SetOrganization(v *Organization) *OrganizationAllowedGroupCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *OrganizationAllowedGroupCreate) SetGroup(v *Group) *OrganizationAllowedGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the OrganizationAllowedGroupMutation object of the builder.
func (_c *OrganizationAllowedGroupCreate) Mutation() *OrganizationAllowedGroupMutation {
	return _c.mutation
}

// Save creates the OrganizationAllowedGroup in the database.
func (_c *OrganizationAllowedGroupCreate) Save(ctx context.Context) (*OrganizationAllowedGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrganizationAllowedGroupCreate) SaveX(ctx context.Context) *OrganizationAllowedGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationAllowedGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationAllowedGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrganizationAllowedGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := organizationallowedgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrganizationAllowedGroupCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "OrganizationAllowedGroup.organization_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "OrganizationAllowedGroup.group_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrganizationAllowedGroup.created_at"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "OrganizationAllowedGroup.organization"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "OrganizationAllowedGroup.group"`)}
	}
	return nil
}

func (_c *OrganizationAllowedGroupCreate) sqlSave(ctx context.Context) (*OrganizationAllowedGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *OrganizationAllowedGroupCreate) createSpec() (*OrganizationAllowedGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &OrganizationAllowedGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(organizationallowedgroup.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(organizationallowedgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationallowedgroup.OrganizationTable,
			Columns: []string{organizationallowedgroup.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationallowedgroup.GroupTable,
			Columns: []string{organizationallowedgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrganizationAllowedGroup.Create().
//		SetOrganizationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrganizationAllowedGroupUpsert) {
//			SetOrganizationID(v+v).
//		}).
//		Exec(ctx)
func (_c *OrganizationAllowedGroupCreate) OnConflict(opts ...sql.ConflictOption) *OrganizationAllowedGroupUpsertOne {
	_c.conflict = opts
	return &OrganizationAllowedGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrganizationAllowedGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrganizationAllowedGroupCreate) OnConflictColumns(columns ...string) *OrganizationAllowedGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrganizationAllowedGroupUpsertOne{
		create: _c,
	}
}

type (
	// OrganizationAllowedGroupUpsertOne is the builder for "upsert"-ing
	//  one OrganizationAllowedGroup node.
	OrganizationAllowedGroupUpsertOne struct {
		create *OrganizationAllowedGroupCreate
	}

	// OrganizationAllowedGroupUpsert is the "OnConflict" setter.
	OrganizationAllowedGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrganizationID sets the "organization_id" field.
func (u *OrganizationAllowedGroupUpsert) SetOrganizationID(v int64) *OrganizationAllowedGroupUpsert {
	u.Set(organizationallowedgroup.FieldOrganizationID, v)
	return u
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *OrganizationAllowedGroupUpsert) UpdateOrganizationID() *OrganizationAllowedGroupUpsert {
	u.SetExcluded(organizationallowedgroup.FieldOrganizationID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *OrganizationAllowedGroupUpsert) SetGroupID(v int64) *OrganizationAllowedGroupUpsert {
	u.Set(organizationallowedgroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OrganizationAllowedGroupUpsert) UpdateGroupID() *OrganizationAllowedGroupUpsert {
	u.SetExcluded(organizationallowedgroup.FieldGroupID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OrganizationAllowedGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrganizationAllowedGroupUpsertOne) UpdateNewValues() *OrganizationAllowedGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(organizationallowedgroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrganizationAllowedGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrganizationAllowedGroupUpsertOne) Ignore() *OrganizationAllowedGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrganizationAllowedGroupUpsertOne) DoNothing() *OrganizationAllowedGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrganizationAllowedGroupCreate.OnConflict
// documentation for more info.
func (u *OrganizationAllowedGroupUpsertOne) Update(set func(*OrganizationAllowedGroupUpsert)) *OrganizationAllowedGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrganizationAllowedGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrganizationID sets the "organization_id" field.
func (u *OrganizationAllowedGroupUpsertOne) SetOrganizationID(v int64) *OrganizationAllowedGroupUpsertOne {
	return u.Update(func(s *OrganizationAllowedGroupUpsert) {
		s.SetOrganizationID(v)
	})
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *OrganizationAllowedGroupUpsertOne) UpdateOrganizationID() *OrganizationAllowedGroupUpsertOne {
	return u.Update(func(s *OrganizationAllowedGroupUpsert) {
		s.UpdateOrganizationID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OrganizationAllowedGroupUpsertOne) SetGroupID(v int64) *OrganizationAllowedGroupUpsertOne {
	return u.Update(func(s *OrganizationAllowedGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OrganizationAllowedGroupUpsertOne) UpdateGroupID() *OrganizationAllowedGroupUpsertOne {
	return u.Update(func(s *OrganizationAllowedGroupUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *OrganizationAllowedGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrganizationAllowedGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrganizationAllowedGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// OrganizationAllowedGroupCreateBulk is the builder for creating many OrganizationAllowedGroup entities in bulk.
type OrganizationAllowedGroupCreateBulk struct {
	config
	err      error
	builders []*OrganizationAllowedGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the OrganizationAllowedGroup entities in the database.
func (_c *OrganizationAllowedGroupCreateBulk) Save(ctx context.Context) ([]*OrganizationAllowedGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrganizationAllowedGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationAllowedGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrganizationAllowedGroupCreateBulk) SaveX(ctx context.Context) []*OrganizationAllowedGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationAllowedGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationAllowedGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrganizationAllowedGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrganizationAllowedGroupUpsert) {
//			SetOrganizationID(v+v).
//		}).
//		Exec(ctx)
func (_c *OrganizationAllowedGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrganizationAllowedGroupUpsertBulk {
	_c.conflict = opts
	return &OrganizationAllowedGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrganizationAllowedGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrganizationAllowedGroupCreateBulk) OnConflictColumns(columns ...string) *OrganizationAllowedGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrganizationAllowedGroupUpsertBulk{
		create: _c,
	}
}

// OrganizationAllowedGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of OrganizationAllowedGroup nodes.
type OrganizationAllowedGroupUpsertBulk struct {
	create *OrganizationAllowedGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OrganizationAllowedGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrganizationAllowedGroupUpsertBulk) UpdateNewValues() *OrganizationAllowedGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(organizationallowedgroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrganizationAllowedGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrganizationAllowedGroupUpsertBulk) Ignore() *OrganizationAllowedGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrganizationAllowedGroupUpsertBulk) DoNothing() *OrganizationAllowedGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrganizationAllowedGroupCreateBulk.OnConflict
// documentation for more info.
func (u *OrganizationAllowedGroupUpsertBulk) Update(set func(*OrganizationAllowedGroupUpsert)) *OrganizationAllowedGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrganizationAllowedGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrganizationID sets the "organization_id" field.
func (u *OrganizationAllowedGroupUpsertBulk) SetOrganizationID(v int64) *OrganizationAllowedGroupUpsertBulk {
	return u.Update(func(s *OrganizationAllowedGroupUpsert) {
		s.SetOrganizationID(v)
	})
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *OrganizationAllowedGroupUpsertBulk) UpdateOrganizationID() *OrganizationAllowedGroupUpsertBulk {
	return u.Update(func(s *OrganizationAllowedGroupUpsert) {
		s.UpdateOrganizationID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OrganizationAllowedGroupUpsertBulk) SetGroupID(v int64) *OrganizationAllowedGroupUpsertBulk {
	return u.Update(func(s *OrganizationAllowedGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OrganizationAllowedGroupUpsertBulk) UpdateGroupID() *OrganizationAllowedGroupUpsertBulk {
	return u.Update(func(s *OrganizationAllowedGroupUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *OrganizationAllowedGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrganizationAllowedGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrganizationAllowedGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrganizationAllowedGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
