// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/organizationquotarequest"
)

// OrganizationQuotaRequest is the model entity for the OrganizationQuotaRequest schema.
type OrganizationQuotaRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID int64 `json:"organization_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// GrantSource holds the value of the "grant_source" field.
	GrantSource *string `json:"grant_source,omitempty"`
	// GrantedAmount holds the value of the "granted_amount" field.
	GrantedAmount *float64 `json:"granted_amount,omitempty"`
	// SnapshotMode holds the value of the "snapshot_mode" field.
	SnapshotMode string `json:"snapshot_mode,omitempty"`
	// SnapshotLimit holds the value of the "snapshot_limit" field.
	SnapshotLimit *float64 `json:"snapshot_limit,omitempty"`
	// SnapshotUsed holds the value of the "snapshot_used" field.
	SnapshotUsed float64 `json:"snapshot_used,omitempty"`
	// ReviewerUserID holds the value of the "reviewer_user_id" field.
	ReviewerUserID *int64 `json:"reviewer_user_id,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
	// ReviewNote holds the value of the "review_note" field.
	ReviewNote   string `json:"review_note,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrganizationQuotaRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case organizationquotarequest.FieldAmount, organizationquotarequest.FieldGrantedAmount, organizationquotarequest.FieldSnapshotLimit, organizationquotarequest.FieldSnapshotUsed:
			values[i] = new(sql.NullFloat64)
		case organizationquotarequest.FieldID, organizationquotarequest.FieldOrganizationID, organizationquotarequest.FieldUserID, organizationquotarequest.FieldReviewerUserID:
			values[i] = new(sql.NullInt64)
		case organizationquotarequest.FieldReason, organizationquotarequest.FieldStatus, organizationquotarequest.FieldGrantSource, organizationquotarequest.FieldSnapshotMode, organizationquotarequest.FieldReviewNote:
			values[i] = new(sql.NullString)
		case organizationquotarequest.FieldCreatedAt, organizationquotarequest.FieldUpdatedAt, organizationquotarequest.FieldReviewedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrganizationQuotaRequest fields.
func (_m *OrganizationQuotaRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case organizationquotarequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case organizationquotarequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case organizationquotarequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case organizationquotarequest.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = value.Int64
			}
		case organizationquotarequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case organizationquotarequest.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case organizationquotarequest.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case organizationquotarequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case organizationquotarequest.FieldGrantSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grant_source", values[i])
			} else if value.Valid {
				_m.GrantSource = new(string)
				*_m.GrantSource = value.String
			}
		case organizationquotarequest.FieldGrantedAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_amount", values[i])
			} else if value.Valid {
				_m.GrantedAmount = new(float64)
				*_m.GrantedAmount = value.Float64
			}
		case organizationquotarequest.FieldSnapshotMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_mode", values[i])
			} else if value.Valid {
				_m.SnapshotMode = value.String
			}
		case organizationquotarequest.FieldSnapshotLimit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_limit", values[i])
			} else if value.Valid {
				_m.SnapshotLimit = new(float64)
				*_m.SnapshotLimit = value.Float64
			}
		case organizationquotarequest.FieldSnapshotUsed:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_used", values[i])
			} else if value.Valid {
				_m.SnapshotUsed = value.Float64
			}
		case organizationquotarequest.FieldReviewerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviewer_user_id", values[i])
			} else if value.Valid {
				_m.ReviewerUserID = new(int64)
				*_m.ReviewerUserID = value.Int64
			}
		case organizationquotarequest.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		case organizationquotarequest.FieldReviewNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_note", values[i])
			} else if value.Valid {
				_m.ReviewNote = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrganizationQuotaRequest.
// This includes values selected through modifiers, order, etc.
func (_m *OrganizationQuotaRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OrganizationQuotaRequest.
// Note that you need to call OrganizationQuotaRequest.Unwrap() before calling this method if this OrganizationQuotaRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrganizationQuotaRequest) Update() *OrganizationQuotaRequestUpdateOne {
	return NewOrganizationQuotaRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrganizationQuotaRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrganizationQuotaRequest) Unwrap() *OrganizationQuotaRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrganizationQuotaRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrganizationQuotaRequest) String() string {
	var builder strings.Builder
	builder.WriteString("OrganizationQuotaRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.GrantSource; v != nil {
		builder.WriteString("grant_source=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GrantedAmount; v != nil {
		builder.WriteString("granted_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("snapshot_mode=")
	builder.WriteString(_m.SnapshotMode)
	builder.WriteString(", ")
	if v := _m.SnapshotLimit; v != nil {
		builder.WriteString("snapshot_limit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("snapshot_used=")
	builder.WriteString(fmt.Sprintf("%v", _m.SnapshotUsed))
	builder.WriteString(", ")
	if v := _m.ReviewerUserID; v != nil {
		builder.WriteString("reviewer_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("review_note=")
	builder.WriteString(_m.ReviewNote)
	builder.WriteByte(')')
	return builder.String()
}

// OrganizationQuotaRequests is a parsable slice of OrganizationQuotaRequest.
type OrganizationQuotaRequests []*OrganizationQuotaRequest
