// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/organizationmember"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OrganizationCreate is the builder for creating a Organization entity.
type OrganizationCreate struct {
	config
	mutation *OrganizationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrganizationCreate) SetCreatedAt(v time.Time) *OrganizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableCreatedAt(v *time.Time) *OrganizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrganizationCreate) SetUpdatedAt(v time.Time) *OrganizationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableUpdatedAt(v *time.Time) *OrganizationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *OrganizationCreate) SetName(v string) *OrganizationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *OrganizationCreate) SetOwnerUserID(v int64) *OrganizationCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetRestrictPublicGroups sets the "restrict_public_groups" field.
func (_c *OrganizationCreate) SetRestrictPublicGroups(v bool) *OrganizationCreate {
	_c.mutation.SetRestrictPublicGroups(v)
	return _c
}

// SetNillableRestrictPublicGroups sets the "restrict_public_groups" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableRestrictPublicGroups(v *bool) *OrganizationCreate {
	if v != nil {
		_c.SetRestrictPublicGroups(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrganizationCreate) SetStatus(v string) *OrganizationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableStatus(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetQuotaRequestMode sets the "quota_request_mode" field.
func (_c *OrganizationCreate) SetQuotaRequestMode(v string) *OrganizationCreate {
	_c.mutation.SetQuotaRequestMode(v)
	return _c
}

// SetNillableQuotaRequestMode sets the "quota_request_mode" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableQuotaRequestMode(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetQuotaRequestMode(*v)
	}
	return _c
}

// SetQuotaRequestMin sets the "quota_request_min" field.
func (_c *OrganizationCreate) SetQuotaRequestMin(v float64) *OrganizationCreate {
	_c.mutation.SetQuotaRequestMin(v)
	return _c
}

// SetNillableQuotaRequestMin sets the "quota_request_min" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableQuotaRequestMin(v *float64) *OrganizationCreate {
	if v != nil {
		_c.SetQuotaRequestMin(*v)
	}
	return _c
}

// SetQuotaRequestMax sets the "quota_request_max" field.
func (_c *OrganizationCreate) SetQuotaRequestMax(v float64) *OrganizationCreate {
	_c.mutation.SetQuotaRequestMax(v)
	return _c
}

// SetNillableQuotaRequestMax sets the "quota_request_max" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableQuotaRequestMax(v *float64) *OrganizationCreate {
	if v != nil {
		_c.SetQuotaRequestMax(*v)
	}
	return _c
}

// SetDefaultQuotaEnabled sets the "default_quota_enabled" field.
func (_c *OrganizationCreate) SetDefaultQuotaEnabled(v bool) *OrganizationCreate {
	_c.mutation.SetDefaultQuotaEnabled(v)
	return _c
}

// SetNillableDefaultQuotaEnabled sets the "default_quota_enabled" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableDefaultQuotaEnabled(v *bool) *OrganizationCreate {
	if v != nil {
		_c.SetDefaultQuotaEnabled(*v)
	}
	return _c
}

// SetDefaultQuotaAmount sets the "default_quota_amount" field.
func (_c *OrganizationCreate) SetDefaultQuotaAmount(v float64) *OrganizationCreate {
	_c.mutation.SetDefaultQuotaAmount(v)
	return _c
}

// SetNillableDefaultQuotaAmount sets the "default_quota_amount" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableDefaultQuotaAmount(v *float64) *OrganizationCreate {
	if v != nil {
		_c.SetDefaultQuotaAmount(*v)
	}
	return _c
}

// SetDefaultQuotaPeriodDays sets the "default_quota_period_days" field.
func (_c *OrganizationCreate) SetDefaultQuotaPeriodDays(v int) *OrganizationCreate {
	_c.mutation.SetDefaultQuotaPeriodDays(v)
	return _c
}

// SetNillableDefaultQuotaPeriodDays sets the "default_quota_period_days" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableDefaultQuotaPeriodDays(v *int) *OrganizationCreate {
	if v != nil {
		_c.SetDefaultQuotaPeriodDays(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *OrganizationCreate) SetOwnerID(id int64) *OrganizationCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *OrganizationCreate) SetOwner(v *User) *OrganizationCreate {
	return _c.SetOwnerID(v.ID)
}

// AddMemberIDs adds the "members" edge to the OrganizationMember entity by IDs.
func (_c *OrganizationCreate) AddMemberIDs(ids ...int64) *OrganizationCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the OrganizationMember entity.
func (_c *OrganizationCreate) AddMembers(v ...*OrganizationMember) *OrganizationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddInvitationIDs adds the "invitations" edge to the RedeemCode entity by IDs.
func (_c *OrganizationCreate) AddInvitationIDs(ids ...int64) *OrganizationCreate {
	_c.mutation.AddInvitationIDs(ids...)
	return _c
}

// AddInvitations adds the "invitations" edges to the RedeemCode entity.
func (_c *OrganizationCreate) AddInvitations(v ...*RedeemCode) *OrganizationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInvitationIDs(ids...)
}

// AddAllowedGroupIDs adds the "allowed_groups" edge to the Group entity by IDs.
func (_c *OrganizationCreate) AddAllowedGroupIDs(ids ...int64) *OrganizationCreate {
	_c.mutation.AddAllowedGroupIDs(ids...)
	return _c
}

// AddAllowedGroups adds the "allowed_groups" edges to the Group entity.
func (_c *OrganizationCreate) AddAllowedGroups(v ...*Group) *OrganizationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAllowedGroupIDs(ids...)
}

// Mutation returns the OrganizationMutation object of the builder.
func (_c *OrganizationCreate) Mutation() *OrganizationMutation {
	return _c.mutation
}

// Save creates the Organization in the database.
func (_c *OrganizationCreate) Save(ctx context.Context) (*Organization, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrganizationCreate) SaveX(ctx context.Context) *Organization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrganizationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := organization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := organization.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RestrictPublicGroups(); !ok {
		v := organization.DefaultRestrictPublicGroups
		_c.mutation.SetRestrictPublicGroups(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := organization.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.QuotaRequestMode(); !ok {
		v := organization.DefaultQuotaRequestMode
		_c.mutation.SetQuotaRequestMode(v)
	}
	if _, ok := _c.mutation.DefaultQuotaEnabled(); !ok {
		v := organization.DefaultDefaultQuotaEnabled
		_c.mutation.SetDefaultQuotaEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrganizationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Organization.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Organization.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Organization.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := organization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Organization.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "Organization.owner_user_id"`)}
	}
	if _, ok := _c.mutation.RestrictPublicGroups(); !ok {
		return &ValidationError{Name: "restrict_public_groups", err: errors.New(`ent: missing required field "Organization.restrict_public_groups"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Organization.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := organization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Organization.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuotaRequestMode(); !ok {
		return &ValidationError{Name: "quota_request_mode", err: errors.New(`ent: missing required field "Organization.quota_request_mode"`)}
	}
	if v, ok := _c.mutation.QuotaRequestMode(); ok {
		if err := organization.QuotaRequestModeValidator(v); err != nil {
			return &ValidationError{Name: "quota_request_mode", err: fmt.Errorf(`ent: validator failed for field "Organization.quota_request_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultQuotaEnabled(); !ok {
		return &ValidationError{Name: "default_quota_enabled", err: errors.New(`ent: missing required field "Organization.default_quota_enabled"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Organization.owner"`)}
	}
	return nil
}

func (_c *OrganizationCreate) sqlSave(ctx context.Context) (*Organization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrganizationCreate) createSpec() (*Organization, *sqlgraph.CreateSpec) {
	var (
		_node = &Organization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(organization.Table, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(organization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(organization.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.RestrictPublicGroups(); ok {
		_spec.SetField(organization.FieldRestrictPublicGroups, field.TypeBool, value)
		_node.RestrictPublicGroups = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(organization.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.QuotaRequestMode(); ok {
		_spec.SetField(organization.FieldQuotaRequestMode, field.TypeString, value)
		_node.QuotaRequestMode = value
	}
	if value, ok := _c.mutation.QuotaRequestMin(); ok {
		_spec.SetField(organization.FieldQuotaRequestMin, field.TypeFloat64, value)
		_node.QuotaRequestMin = &value
	}
	if value, ok := _c.mutation.QuotaRequestMax(); ok {
		_spec.SetField(organization.FieldQuotaRequestMax, field.TypeFloat64, value)
		_node.QuotaRequestMax = &value
	}
	if value, ok := _c.mutation.DefaultQuotaEnabled(); ok {
		_spec.SetField(organization.FieldDefaultQuotaEnabled, field.TypeBool, value)
		_node.DefaultQuotaEnabled = value
	}
	if value, ok := _c.mutation.DefaultQuotaAmount(); ok {
		_spec.SetField(organization.FieldDefaultQuotaAmount, field.TypeFloat64, value)
		_node.DefaultQuotaAmount = &value
	}
	if value, ok := _c.mutation.DefaultQuotaPeriodDays(); ok {
		_spec.SetField(organization.FieldDefaultQuotaPeriodDays, field.TypeInt, value)
		_node.DefaultQuotaPeriodDays = &value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   organization.OwnerTable,
			Columns: []string{organization.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.InvitationsTable,
			Columns: []string{organization.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AllowedGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   organization.AllowedGroupsTable,
			Columns: organization.AllowedGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &OrganizationAllowedGroupCreate{config: _c.config, mutation: newOrganizationAllowedGroupMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Organization.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrganizationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrganizationCreate) OnConflict(opts ...sql.ConflictOption) *OrganizationUpsertOne {
	_c.conflict = opts
	return &OrganizationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Organization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrganizationCreate) OnConflictColumns(columns ...string) *OrganizationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrganizationUpsertOne{
		create: _c,
	}
}

type (
	// OrganizationUpsertOne is the builder for "upsert"-ing
	//  one Organization node.
	OrganizationUpsertOne struct {
		create *OrganizationCreate
	}

	// OrganizationUpsert is the "OnConflict" setter.
	OrganizationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationUpsert) SetUpdatedAt(v time.Time) *OrganizationUpsert {
	u.Set(organization.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateUpdatedAt() *OrganizationUpsert {
	u.SetExcluded(organization.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *OrganizationUpsert) SetName(v string) *OrganizationUpsert {
	u.Set(organization.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateName() *OrganizationUpsert {
	u.SetExcluded(organization.FieldName)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *OrganizationUpsert) SetOwnerUserID(v int64) *OrganizationUpsert {
	u.Set(organization.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateOwnerUserID() *OrganizationUpsert {
	u.SetExcluded(organization.FieldOwnerUserID)
	return u
}

// SetRestrictPublicGroups sets the "restrict_public_groups" field.
func (u *OrganizationUpsert) SetRestrictPublicGroups(v bool) *OrganizationUpsert {
	u.Set(organization.FieldRestrictPublicGroups, v)
	return u
}

// UpdateRestrictPublicGroups sets the "restrict_public_groups" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateRestrictPublicGroups() *OrganizationUpsert {
	u.SetExcluded(organization.FieldRestrictPublicGroups)
	return u
}

// SetStatus sets the "status" field.
func (u *OrganizationUpsert) SetStatus(v string) *OrganizationUpsert {
	u.Set(organization.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateStatus() *OrganizationUpsert {
	u.SetExcluded(organization.FieldStatus)
	return u
}

// SetQuotaRequestMode sets the "quota_request_mode" field.
func (u *OrganizationUpsert) SetQuotaRequestMode(v string) *OrganizationUpsert {
	u.Set(organization.FieldQuotaRequestMode, v)
	return u
}

// UpdateQuotaRequestMode sets the "quota_request_mode" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateQuotaRequestMode() *OrganizationUpsert {
	u.SetExcluded(organization.FieldQuotaRequestMode)
	return u
}

// SetQuotaRequestMin sets the "quota_request_min" field.
func (u *OrganizationUpsert) SetQuotaRequestMin(v float64) *OrganizationUpsert {
	u.Set(organization.FieldQuotaRequestMin, v)
	return u
}

// UpdateQuotaRequestMin sets the "quota_request_min" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateQuotaRequestMin() *OrganizationUpsert {
	u.SetExcluded(organization.FieldQuotaRequestMin)
	return u
}

// AddQuotaRequestMin adds v to the "quota_request_min" field.
func (u *OrganizationUpsert) AddQuotaRequestMin(v float64) *OrganizationUpsert {
	u.Add(organization.FieldQuotaRequestMin, v)
	return u
}

// ClearQuotaRequestMin clears the value of the "quota_request_min" field.
func (u *OrganizationUpsert) ClearQuotaRequestMin() *OrganizationUpsert {
	u.SetNull(organization.FieldQuotaRequestMin)
	return u
}

// SetQuotaRequestMax sets the "quota_request_max" field.
func (u *OrganizationUpsert) SetQuotaRequestMax(v float64) *OrganizationUpsert {
	u.Set(organization.FieldQuotaRequestMax, v)
	return u
}

// UpdateQuotaRequestMax sets the "quota_request_max" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateQuotaRequestMax() *OrganizationUpsert {
	u.SetExcluded(organization.FieldQuotaRequestMax)
	return u
}

// AddQuotaRequestMax adds v to the "quota_request_max" field.
func (u *OrganizationUpsert) AddQuotaRequestMax(v float64) *OrganizationUpsert {
	u.Add(organization.FieldQuotaRequestMax, v)
	return u
}

// ClearQuotaRequestMax clears the value of the "quota_request_max" field.
func (u *OrganizationUpsert) ClearQuotaRequestMax() *OrganizationUpsert {
	u.SetNull(organization.FieldQuotaRequestMax)
	return u
}

// SetDefaultQuotaEnabled sets the "default_quota_enabled" field.
func (u *OrganizationUpsert) SetDefaultQuotaEnabled(v bool) *OrganizationUpsert {
	u.Set(organization.FieldDefaultQuotaEnabled, v)
	return u
}

// UpdateDefaultQuotaEnabled sets the "default_quota_enabled" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateDefaultQuotaEnabled() *OrganizationUpsert {
	u.SetExcluded(organization.FieldDefaultQuotaEnabled)
	return u
}

// SetDefaultQuotaAmount sets the "default_quota_amount" field.
func (u *OrganizationUpsert) SetDefaultQuotaAmount(v float64) *OrganizationUpsert {
	u.Set(organization.FieldDefaultQuotaAmount, v)
	return u
}

// UpdateDefaultQuotaAmount sets the "default_quota_amount" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateDefaultQuotaAmount() *OrganizationUpsert {
	u.SetExcluded(organization.FieldDefaultQuotaAmount)
	return u
}

// AddDefaultQuotaAmount adds v to the "default_quota_amount" field.
func (u *OrganizationUpsert) AddDefaultQuotaAmount(v float64) *OrganizationUpsert {
	u.Add(organization.FieldDefaultQuotaAmount, v)
	return u
}

// ClearDefaultQuotaAmount clears the value of the "default_quota_amount" field.
func (u *OrganizationUpsert) ClearDefaultQuotaAmount() *OrganizationUpsert {
	u.SetNull(organization.FieldDefaultQuotaAmount)
	return u
}

// SetDefaultQuotaPeriodDays sets the "default_quota_period_days" field.
func (u *OrganizationUpsert) SetDefaultQuotaPeriodDays(v int) *OrganizationUpsert {
	u.Set(organization.FieldDefaultQuotaPeriodDays, v)
	return u
}

// UpdateDefaultQuotaPeriodDays sets the "default_quota_period_days" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateDefaultQuotaPeriodDays() *OrganizationUpsert {
	u.SetExcluded(organization.FieldDefaultQuotaPeriodDays)
	return u
}

// AddDefaultQuotaPeriodDays adds v to the "default_quota_period_days" field.
func (u *OrganizationUpsert) AddDefaultQuotaPeriodDays(v int) *OrganizationUpsert {
	u.Add(organization.FieldDefaultQuotaPeriodDays, v)
	return u
}

// ClearDefaultQuotaPeriodDays clears the value of the "default_quota_period_days" field.
func (u *OrganizationUpsert) ClearDefaultQuotaPeriodDays() *OrganizationUpsert {
	u.SetNull(organization.FieldDefaultQuotaPeriodDays)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Organization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrganizationUpsertOne) UpdateNewValues() *OrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(organization.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Organization.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrganizationUpsertOne) Ignore() *OrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrganizationUpsertOne) DoNothing() *OrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrganizationCreate.OnConflict
// documentation for more info.
func (u *OrganizationUpsertOne) Update(set func(*OrganizationUpsert)) *OrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrganizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationUpsertOne) SetUpdatedAt(v time.Time) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateUpdatedAt() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *OrganizationUpsertOne) SetName(v string) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateName() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateName()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *OrganizationUpsertOne) SetOwnerUserID(v int64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateOwnerUserID() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetRestrictPublicGroups sets the "restrict_public_groups" field.
func (u *OrganizationUpsertOne) SetRestrictPublicGroups(v bool) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetRestrictPublicGroups(v)
	})
}

// UpdateRestrictPublicGroups sets the "restrict_public_groups" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateRestrictPublicGroups() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateRestrictPublicGroups()
	})
}

// SetStatus sets the "status" field.
func (u *OrganizationUpsertOne) SetStatus(v string) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateStatus() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateStatus()
	})
}

// SetQuotaRequestMode sets the "quota_request_mode" field.
func (u *OrganizationUpsertOne) SetQuotaRequestMode(v string) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetQuotaRequestMode(v)
	})
}

// UpdateQuotaRequestMode sets the "quota_request_mode" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateQuotaRequestMode() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateQuotaRequestMode()
	})
}

// SetQuotaRequestMin sets the "quota_request_min" field.
func (u *OrganizationUpsertOne) SetQuotaRequestMin(v float64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetQuotaRequestMin(v)
	})
}

// AddQuotaRequestMin adds v to the "quota_request_min" field.
func (u *OrganizationUpsertOne) AddQuotaRequestMin(v float64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddQuotaRequestMin(v)
	})
}

// UpdateQuotaRequestMin sets the "quota_request_min" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateQuotaRequestMin() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateQuotaRequestMin()
	})
}

// ClearQuotaRequestMin clears the value of the "quota_request_min" field.
func (u *OrganizationUpsertOne) ClearQuotaRequestMin() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearQuotaRequestMin()
	})
}

// SetQuotaRequestMax sets the "quota_request_max" field.
func (u *OrganizationUpsertOne) SetQuotaRequestMax(v float64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetQuotaRequestMax(v)
	})
}

// AddQuotaRequestMax adds v to the "quota_request_max" field.
func (u *OrganizationUpsertOne) AddQuotaRequestMax(v float64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddQuotaRequestMax(v)
	})
}

// UpdateQuotaRequestMax sets the "quota_request_max" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateQuotaRequestMax() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateQuotaRequestMax()
	})
}

// ClearQuotaRequestMax clears the value of the "quota_request_max" field.
func (u *OrganizationUpsertOne) ClearQuotaRequestMax() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearQuotaRequestMax()
	})
}

// SetDefaultQuotaEnabled sets the "default_quota_enabled" field.
func (u *OrganizationUpsertOne) SetDefaultQuotaEnabled(v bool) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetDefaultQuotaEnabled(v)
	})
}

// UpdateDefaultQuotaEnabled sets the "default_quota_enabled" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateDefaultQuotaEnabled() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateDefaultQuotaEnabled()
	})
}

// SetDefaultQuotaAmount sets the "default_quota_amount" field.
func (u *OrganizationUpsertOne) SetDefaultQuotaAmount(v float64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetDefaultQuotaAmount(v)
	})
}

// AddDefaultQuotaAmount adds v to the "default_quota_amount" field.
func (u *OrganizationUpsertOne) AddDefaultQuotaAmount(v float64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddDefaultQuotaAmount(v)
	})
}

// UpdateDefaultQuotaAmount sets the "default_quota_amount" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateDefaultQuotaAmount() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateDefaultQuotaAmount()
	})
}

// ClearDefaultQuotaAmount clears the value of the "default_quota_amount" field.
func (u *OrganizationUpsertOne) ClearDefaultQuotaAmount() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearDefaultQuotaAmount()
	})
}

// SetDefaultQuotaPeriodDays sets the "default_quota_period_days" field.
func (u *OrganizationUpsertOne) SetDefaultQuotaPeriodDays(v int) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetDefaultQuotaPeriodDays(v)
	})
}

// AddDefaultQuotaPeriodDays adds v to the "default_quota_period_days" field.
func (u *OrganizationUpsertOne) AddDefaultQuotaPeriodDays(v int) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddDefaultQuotaPeriodDays(v)
	})
}

// UpdateDefaultQuotaPeriodDays sets the "default_quota_period_days" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateDefaultQuotaPeriodDays() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateDefaultQuotaPeriodDays()
	})
}

// ClearDefaultQuotaPeriodDays clears the value of the "default_quota_period_days" field.
func (u *OrganizationUpsertOne) ClearDefaultQuotaPeriodDays() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearDefaultQuotaPeriodDays()
	})
}

// Exec executes the query.
func (u *OrganizationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrganizationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrganizationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrganizationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrganizationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrganizationCreateBulk is the builder for creating many Organization entities in bulk.
type OrganizationCreateBulk struct {
	config
	err      error
	builders []*OrganizationCreate
	conflict []sql.ConflictOption
}

// Save creates the Organization entities in the database.
func (_c *OrganizationCreateBulk) Save(ctx context.Context) ([]*Organization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Organization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrganizationCreateBulk) SaveX(ctx context.Context) []*Organization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Organization.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrganizationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrganizationCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrganizationUpsertBulk {
	_c.conflict = opts
	return &OrganizationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Organization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrganizationCreateBulk) OnConflictColumns(columns ...string) *OrganizationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrganizationUpsertBulk{
		create: _c,
	}
}

// OrganizationUpsertBulk is the builder for "upsert"-ing
// a bulk of Organization nodes.
type OrganizationUpsertBulk struct {
	create *OrganizationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Organization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrganizationUpsertBulk) UpdateNewValues() *OrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(organization.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Organization.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrganizationUpsertBulk) Ignore() *OrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrganizationUpsertBulk) DoNothing() *OrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrganizationCreateBulk.OnConflict
// documentation for more info.
func (u *OrganizationUpsertBulk) Update(set func(*OrganizationUpsert)) *OrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrganizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationUpsertBulk) SetUpdatedAt(v time.Time) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateUpdatedAt() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *OrganizationUpsertBulk) SetName(v string) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateName() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateName()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *OrganizationUpsertBulk) SetOwnerUserID(v int64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateOwnerUserID() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetRestrictPublicGroups sets the "restrict_public_groups" field.
func (u *OrganizationUpsertBulk) SetRestrictPublicGroups(v bool) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetRestrictPublicGroups(v)
	})
}

// UpdateRestrictPublicGroups sets the "restrict_public_groups" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateRestrictPublicGroups() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateRestrictPublicGroups()
	})
}

// SetStatus sets the "status" field.
func (u *OrganizationUpsertBulk) SetStatus(v string) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateStatus() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateStatus()
	})
}

// SetQuotaRequestMode sets the "quota_request_mode" field.
func (u *OrganizationUpsertBulk) SetQuotaRequestMode(v string) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetQuotaRequestMode(v)
	})
}

// UpdateQuotaRequestMode sets the "quota_request_mode" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateQuotaRequestMode() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateQuotaRequestMode()
	})
}

// SetQuotaRequestMin sets the "quota_request_min" field.
func (u *OrganizationUpsertBulk) SetQuotaRequestMin(v float64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetQuotaRequestMin(v)
	})
}

// AddQuotaRequestMin adds v to the "quota_request_min" field.
func (u *OrganizationUpsertBulk) AddQuotaRequestMin(v float64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddQuotaRequestMin(v)
	})
}

// UpdateQuotaRequestMin sets the "quota_request_min" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateQuotaRequestMin() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateQuotaRequestMin()
	})
}

// ClearQuotaRequestMin clears the value of the "quota_request_min" field.
func (u *OrganizationUpsertBulk) ClearQuotaRequestMin() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearQuotaRequestMin()
	})
}

// SetQuotaRequestMax sets the "quota_request_max" field.
func (u *OrganizationUpsertBulk) SetQuotaRequestMax(v float64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetQuotaRequestMax(v)
	})
}

// AddQuotaRequestMax adds v to the "quota_request_max" field.
func (u *OrganizationUpsertBulk) AddQuotaRequestMax(v float64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddQuotaRequestMax(v)
	})
}

// UpdateQuotaRequestMax sets the "quota_request_max" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateQuotaRequestMax() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateQuotaRequestMax()
	})
}

// ClearQuotaRequestMax clears the value of the "quota_request_max" field.
func (u *OrganizationUpsertBulk) ClearQuotaRequestMax() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearQuotaRequestMax()
	})
}

// SetDefaultQuotaEnabled sets the "default_quota_enabled" field.
func (u *OrganizationUpsertBulk) SetDefaultQuotaEnabled(v bool) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetDefaultQuotaEnabled(v)
	})
}

// UpdateDefaultQuotaEnabled sets the "default_quota_enabled" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateDefaultQuotaEnabled() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateDefaultQuotaEnabled()
	})
}

// SetDefaultQuotaAmount sets the "default_quota_amount" field.
func (u *OrganizationUpsertBulk) SetDefaultQuotaAmount(v float64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetDefaultQuotaAmount(v)
	})
}

// AddDefaultQuotaAmount adds v to the "default_quota_amount" field.
func (u *OrganizationUpsertBulk) AddDefaultQuotaAmount(v float64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddDefaultQuotaAmount(v)
	})
}

// UpdateDefaultQuotaAmount sets the "default_quota_amount" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateDefaultQuotaAmount() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateDefaultQuotaAmount()
	})
}

// ClearDefaultQuotaAmount clears the value of the "default_quota_amount" field.
func (u *OrganizationUpsertBulk) ClearDefaultQuotaAmount() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearDefaultQuotaAmount()
	})
}

// SetDefaultQuotaPeriodDays sets the "default_quota_period_days" field.
func (u *OrganizationUpsertBulk) SetDefaultQuotaPeriodDays(v int) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetDefaultQuotaPeriodDays(v)
	})
}

// AddDefaultQuotaPeriodDays adds v to the "default_quota_period_days" field.
func (u *OrganizationUpsertBulk) AddDefaultQuotaPeriodDays(v int) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddDefaultQuotaPeriodDays(v)
	})
}

// UpdateDefaultQuotaPeriodDays sets the "default_quota_period_days" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateDefaultQuotaPeriodDays() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateDefaultQuotaPeriodDays()
	})
}

// ClearDefaultQuotaPeriodDays clears the value of the "default_quota_period_days" field.
func (u *OrganizationUpsertBulk) ClearDefaultQuotaPeriodDays() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearDefaultQuotaPeriodDays()
	})
}

// Exec executes the query.
func (u *OrganizationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrganizationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrganizationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrganizationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
