// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/organizationmember"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OrganizationUpdate is the builder for updating Organization entities.
type OrganizationUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationMutation
}

// Where appends a list predicates to the OrganizationUpdate builder.
func (_u *OrganizationUpdate) Where(ps ...predicate.Organization) *OrganizationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationUpdate) SetUpdatedAt(v time.Time) *OrganizationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *OrganizationUpdate) SetName(v string) *OrganizationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableName(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *OrganizationUpdate) SetOwnerUserID(v int64) *OrganizationUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableOwnerUserID(v *int64) *OrganizationUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetRestrictPublicGroups sets the "restrict_public_groups" field.
func (_u *OrganizationUpdate) SetRestrictPublicGroups(v bool) *OrganizationUpdate {
	_u.mutation.SetRestrictPublicGroups(v)
	return _u
}

// SetNillableRestrictPublicGroups sets the "restrict_public_groups" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableRestrictPublicGroups(v *bool) *OrganizationUpdate {
	if v != nil {
		_u.SetRestrictPublicGroups(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrganizationUpdate) SetStatus(v string) *OrganizationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableStatus(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetQuotaRequestMode sets the "quota_request_mode" field.
func (_u *OrganizationUpdate) SetQuotaRequestMode(v string) *OrganizationUpdate {
	_u.mutation.SetQuotaRequestMode(v)
	return _u
}

// SetNillableQuotaRequestMode sets the "quota_request_mode" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableQuotaRequestMode(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetQuotaRequestMode(*v)
	}
	return _u
}

// SetQuotaRequestMin sets the "quota_request_min" field.
func (_u *OrganizationUpdate) SetQuotaRequestMin(v float64) *OrganizationUpdate {
	_u.mutation.ResetQuotaRequestMin()
	_u.mutation.SetQuotaRequestMin(v)
	return _u
}

// SetNillableQuotaRequestMin sets the "quota_request_min" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableQuotaRequestMin(v *float64) *OrganizationUpdate {
	if v != nil {
		_u.SetQuotaRequestMin(*v)
	}
	return _u
}

// AddQuotaRequestMin adds value to the "quota_request_min" field.
func (_u *OrganizationUpdate) AddQuotaRequestMin(v float64) *OrganizationUpdate {
	_u.mutation.AddQuotaRequestMin(v)
	return _u
}

// ClearQuotaRequestMin clears the value of the "quota_request_min" field.
func (_u *OrganizationUpdate) ClearQuotaRequestMin() *OrganizationUpdate {
	_u.mutation.ClearQuotaRequestMin()
	return _u
}

// SetQuotaRequestMax sets the "quota_request_max" field.
func (_u *OrganizationUpdate) SetQuotaRequestMax(v float64) *OrganizationUpdate {
	_u.mutation.ResetQuotaRequestMax()
	_u.mutation.SetQuotaRequestMax(v)
	return _u
}

// SetNillableQuotaRequestMax sets the "quota_request_max" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableQuotaRequestMax(v *float64) *OrganizationUpdate {
	if v != nil {
		_u.SetQuotaRequestMax(*v)
	}
	return _u
}

// AddQuotaRequestMax adds value to the "quota_request_max" field.
func (_u *OrganizationUpdate) AddQuotaRequestMax(v float64) *OrganizationUpdate {
	_u.mutation.AddQuotaRequestMax(v)
	return _u
}

// ClearQuotaRequestMax clears the value of the "quota_request_max" field.
func (_u *OrganizationUpdate) ClearQuotaRequestMax() *OrganizationUpdate {
	_u.mutation.ClearQuotaRequestMax()
	return _u
}

// SetDefaultQuotaEnabled sets the "default_quota_enabled" field.
func (_u *OrganizationUpdate) SetDefaultQuotaEnabled(v bool) *OrganizationUpdate {
	_u.mutation.SetDefaultQuotaEnabled(v)
	return _u
}

// SetNillableDefaultQuotaEnabled sets the "default_quota_enabled" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableDefaultQuotaEnabled(v *bool) *OrganizationUpdate {
	if v != nil {
		_u.SetDefaultQuotaEnabled(*v)
	}
	return _u
}

// SetDefaultQuotaAmount sets the "default_quota_amount" field.
func (_u *OrganizationUpdate) SetDefaultQuotaAmount(v float64) *OrganizationUpdate {
	_u.mutation.ResetDefaultQuotaAmount()
	_u.mutation.SetDefaultQuotaAmount(v)
	return _u
}

// SetNillableDefaultQuotaAmount sets the "default_quota_amount" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableDefaultQuotaAmount(v *float64) *OrganizationUpdate {
	if v != nil {
		_u.SetDefaultQuotaAmount(*v)
	}
	return _u
}

// AddDefaultQuotaAmount adds value to the "default_quota_amount" field.
func (_u *OrganizationUpdate) AddDefaultQuotaAmount(v float64) *OrganizationUpdate {
	_u.mutation.AddDefaultQuotaAmount(v)
	return _u
}

// ClearDefaultQuotaAmount clears the value of the "default_quota_amount" field.
func (_u *OrganizationUpdate) ClearDefaultQuotaAmount() *OrganizationUpdate {
	_u.mutation.ClearDefaultQuotaAmount()
	return _u
}

// SetDefaultQuotaPeriodDays sets the "default_quota_period_days" field.
func (_u *OrganizationUpdate) SetDefaultQuotaPeriodDays(v int) *OrganizationUpdate {
	_u.mutation.ResetDefaultQuotaPeriodDays()
	_u.mutation.SetDefaultQuotaPeriodDays(v)
	return _u
}

// SetNillableDefaultQuotaPeriodDays sets the "default_quota_period_days" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableDefaultQuotaPeriodDays(v *int) *OrganizationUpdate {
	if v != nil {
		_u.SetDefaultQuotaPeriodDays(*v)
	}
	return _u
}

// AddDefaultQuotaPeriodDays adds value to the "default_quota_period_days" field.
func (_u *OrganizationUpdate) AddDefaultQuotaPeriodDays(v int) *OrganizationUpdate {
	_u.mutation.AddDefaultQuotaPeriodDays(v)
	return _u
}

// ClearDefaultQuotaPeriodDays clears the value of the "default_quota_period_days" field.
func (_u *OrganizationUpdate) ClearDefaultQuotaPeriodDays() *OrganizationUpdate {
	_u.mutation.ClearDefaultQuotaPeriodDays()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *OrganizationUpdate) SetOwnerID(id int64) *OrganizationUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *OrganizationUpdate) SetOwner(v *User) *OrganizationUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddMemberIDs adds the "members" edge to the OrganizationMember entity by IDs.
func (_u *OrganizationUpdate) AddMemberIDs(ids ...int64) *OrganizationUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the OrganizationMember entity.
func (_u *OrganizationUpdate) AddMembers(v ...*OrganizationMember) *OrganizationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddInvitationIDs adds the "invitations" edge to the RedeemCode entity by IDs.
func (_u *OrganizationUpdate) AddInvitationIDs(ids ...int64) *OrganizationUpdate {
	_u.mutation.AddInvitationIDs(ids...)
	return _u
}

// AddInvitations adds the "invitations" edges to the RedeemCode entity.
func (_u *OrganizationUpdate) AddInvitations(v ...*RedeemCode) *OrganizationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvitationIDs(ids...)
}

// AddAllowedGroupIDs adds the "allowed_groups" edge to the Group entity by IDs.
func (_u *OrganizationUpdate) AddAllowedGroupIDs(ids ...int64) *OrganizationUpdate {
	_u.mutation.AddAllowedGroupIDs(ids...)
	return _u
}

// AddAllowedGroups adds the "allowed_groups" edges to the Group entity.
func (_u *OrganizationUpdate) AddAllowedGroups(v ...*Group) *OrganizationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAllowedGroupIDs(ids...)
}

// Mutation returns the OrganizationMutation object of the builder.
func (_u *OrganizationUpdate) Mutation() *OrganizationMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *OrganizationUpdate) ClearOwner() *OrganizationUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMembers clears all "members" edges to the OrganizationMember entity.
func (_u *OrganizationUpdate) ClearMembers() *OrganizationUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to OrganizationMember entities by IDs.
func (_u *OrganizationUpdate) RemoveMemberIDs(ids ...int64) *OrganizationUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to OrganizationMember entities.
func (_u *OrganizationUpdate) RemoveMembers(v ...*OrganizationMember) *OrganizationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearInvitations clears all "invitations" edges to the RedeemCode entity.
func (_u *OrganizationUpdate) ClearInvitations() *OrganizationUpdate {
	_u.mutation.ClearInvitations()
	return _u
}

// RemoveInvitationIDs removes the "invitations" edge to RedeemCode entities by IDs.
func (_u *OrganizationUpdate) RemoveInvitationIDs(ids ...int64) *OrganizationUpdate {
	_u.mutation.RemoveInvitationIDs(ids...)
	return _u
}

// RemoveInvitations removes "invitations" edges to RedeemCode entities.
func (_u *OrganizationUpdate) RemoveInvitations(v ...*RedeemCode) *OrganizationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvitationIDs(ids...)
}

// ClearAllowedGroups clears all "allowed_groups" edges to the Group entity.
func (_u *OrganizationUpdate) ClearAllowedGroups() *OrganizationUpdate {
	_u.mutation.ClearAllowedGroups()
	return _u
}

// RemoveAllowedGroupIDs removes the "allowed_groups" edge to Group entities by IDs.
func (_u *OrganizationUpdate) RemoveAllowedGroupIDs(ids ...int64) *OrganizationUpdate {
	_u.mutation.RemoveAllowedGroupIDs(ids...)
	return _u
}

// RemoveAllowedGroups removes "allowed_groups" edges to Group entities.
func (_u *OrganizationUpdate) RemoveAllowedGroups(v ...*Group) *OrganizationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAllowedGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrganizationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrganizationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := organization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := organization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Organization.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := organization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Organization.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaRequestMode(); ok {
		if err := organization.QuotaRequestModeValidator(v); err != nil {
			return &ValidationError{Name: "quota_request_mode", err: fmt.Errorf(`ent: validator failed for field "Organization.quota_request_mode": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Organization.owner"`)
	}
	return nil
}

func (_u *OrganizationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organization.Table, organization.Columns, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(organization.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RestrictPublicGroups(); ok {
		_spec.SetField(organization.FieldRestrictPublicGroups, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(organization.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaRequestMode(); ok {
		_spec.SetField(organization.FieldQuotaRequestMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaRequestMin(); ok {
		_spec.SetField(organization.FieldQuotaRequestMin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaRequestMin(); ok {
		_spec.AddField(organization.FieldQuotaRequestMin, field.TypeFloat64, value)
	}
	if _u.mutation.QuotaRequestMinCleared() {
		_spec.ClearField(organization.FieldQuotaRequestMin, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QuotaRequestMax(); ok {
		_spec.SetField(organization.FieldQuotaRequestMax, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaRequestMax(); ok {
		_spec.AddField(organization.FieldQuotaRequestMax, field.TypeFloat64, value)
	}
	if _u.mutation.QuotaRequestMaxCleared() {
		_spec.ClearField(organization.FieldQuotaRequestMax, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DefaultQuotaEnabled(); ok {
		_spec.SetField(organization.FieldDefaultQuotaEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultQuotaAmount(); ok {
		_spec.SetField(organization.FieldDefaultQuotaAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultQuotaAmount(); ok {
		_spec.AddField(organization.FieldDefaultQuotaAmount, field.TypeFloat64, value)
	}
	if _u.mutation.DefaultQuotaAmountCleared() {
		_spec.ClearField(organization.FieldDefaultQuotaAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DefaultQuotaPeriodDays(); ok {
		_spec.SetField(organization.FieldDefaultQuotaPeriodDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDefaultQuotaPeriodDays(); ok {
		_spec.AddField(organization.FieldDefaultQuotaPeriodDays, field.TypeInt, value)
	}
	if _u.mutation.DefaultQuotaPeriodDaysCleared() {
		_spec.ClearField(organization.FieldDefaultQuotaPeriodDays, field.TypeInt)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   organization.OwnerTable,
			Columns: []string{organization.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   organization.OwnerTable,
			Columns: []string{organization.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.InvitationsTable,
			Columns: []string{organization.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvitationsIDs(); len(nodes) > 0 && !_u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.InvitationsTable,
			Columns: []string{organization.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.InvitationsTable,
			Columns: []string{organization.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AllowedGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   organization.AllowedGroupsTable,
			Columns: organization.AllowedGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		createE := &OrganizationAllowedGroupCreate{config: _u.config, mutation: newOrganizationAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAllowedGroupsIDs(); len(nodes) > 0 && !_u.mutation.AllowedGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   organization.AllowedGroupsTable,
			Columns: organization.AllowedGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &OrganizationAllowedGroupCreate{config: _u.config, mutation: newOrganizationAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AllowedGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   organization.AllowedGroupsTable,
			Columns: organization.AllowedGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &OrganizationAllowedGroupCreate{config: _u.config, mutation: newOrganizationAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrganizationUpdateOne is the builder for updating a single Organization entity.
type OrganizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationUpdateOne) SetUpdatedAt(v time.Time) *OrganizationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *OrganizationUpdateOne) SetName(v string) *OrganizationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableName(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *OrganizationUpdateOne) SetOwnerUserID(v int64) *OrganizationUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableOwnerUserID(v *int64) *OrganizationUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetRestrictPublicGroups sets the "restrict_public_groups" field.
func (_u *OrganizationUpdateOne) SetRestrictPublicGroups(v bool) *OrganizationUpdateOne {
	_u.mutation.SetRestrictPublicGroups(v)
	return _u
}

// SetNillableRestrictPublicGroups sets the "restrict_public_groups" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableRestrictPublicGroups(v *bool) *OrganizationUpdateOne {
	if v != nil {
		_u.SetRestrictPublicGroups(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrganizationUpdateOne) SetStatus(v string) *OrganizationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableStatus(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetQuotaRequestMode sets the "quota_request_mode" field.
func (_u *OrganizationUpdateOne) SetQuotaRequestMode(v string) *OrganizationUpdateOne {
	_u.mutation.SetQuotaRequestMode(v)
	return _u
}

// SetNillableQuotaRequestMode sets the "quota_request_mode" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableQuotaRequestMode(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetQuotaRequestMode(*v)
	}
	return _u
}

// SetQuotaRequestMin sets the "quota_request_min" field.
func (_u *OrganizationUpdateOne) SetQuotaRequestMin(v float64) *OrganizationUpdateOne {
	_u.mutation.ResetQuotaRequestMin()
	_u.mutation.SetQuotaRequestMin(v)
	return _u
}

// SetNillableQuotaRequestMin sets the "quota_request_min" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableQuotaRequestMin(v *float64) *OrganizationUpdateOne {
	if v != nil {
		_u.SetQuotaRequestMin(*v)
	}
	return _u
}

// AddQuotaRequestMin adds value to the "quota_request_min" field.
func (_u *OrganizationUpdateOne) AddQuotaRequestMin(v float64) *OrganizationUpdateOne {
	_u.mutation.AddQuotaRequestMin(v)
	return _u
}

// ClearQuotaRequestMin clears the value of the "quota_request_min" field.
func (_u *OrganizationUpdateOne) ClearQuotaRequestMin() *OrganizationUpdateOne {
	_u.mutation.ClearQuotaRequestMin()
	return _u
}

// SetQuotaRequestMax sets the "quota_request_max" field.
func (_u *OrganizationUpdateOne) SetQuotaRequestMax(v float64) *OrganizationUpdateOne {
	_u.mutation.ResetQuotaRequestMax()
	_u.mutation.SetQuotaRequestMax(v)
	return _u
}

// SetNillableQuotaRequestMax sets the "quota_request_max" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableQuotaRequestMax(v *float64) *OrganizationUpdateOne {
	if v != nil {
		_u.SetQuotaRequestMax(*v)
	}
	return _u
}

// AddQuotaRequestMax adds value to the "quota_request_max" field.
func (_u *OrganizationUpdateOne) AddQuotaRequestMax(v float64) *OrganizationUpdateOne {
	_u.mutation.AddQuotaRequestMax(v)
	return _u
}

// ClearQuotaRequestMax clears the value of the "quota_request_max" field.
func (_u *OrganizationUpdateOne) ClearQuotaRequestMax() *OrganizationUpdateOne {
	_u.mutation.ClearQuotaRequestMax()
	return _u
}

// SetDefaultQuotaEnabled sets the "default_quota_enabled" field.
func (_u *OrganizationUpdateOne) SetDefaultQuotaEnabled(v bool) *OrganizationUpdateOne {
	_u.mutation.SetDefaultQuotaEnabled(v)
	return _u
}

// SetNillableDefaultQuotaEnabled sets the "default_quota_enabled" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableDefaultQuotaEnabled(v *bool) *OrganizationUpdateOne {
	if v != nil {
		_u.SetDefaultQuotaEnabled(*v)
	}
	return _u
}

// SetDefaultQuotaAmount sets the "default_quota_amount" field.
func (_u *OrganizationUpdateOne) SetDefaultQuotaAmount(v float64) *OrganizationUpdateOne {
	_u.mutation.ResetDefaultQuotaAmount()
	_u.mutation.SetDefaultQuotaAmount(v)
	return _u
}

// SetNillableDefaultQuotaAmount sets the "default_quota_amount" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableDefaultQuotaAmount(v *float64) *OrganizationUpdateOne {
	if v != nil {
		_u.SetDefaultQuotaAmount(*v)
	}
	return _u
}

// AddDefaultQuotaAmount adds value to the "default_quota_amount" field.
func (_u *OrganizationUpdateOne) AddDefaultQuotaAmount(v float64) *OrganizationUpdateOne {
	_u.mutation.AddDefaultQuotaAmount(v)
	return _u
}

// ClearDefaultQuotaAmount clears the value of the "default_quota_amount" field.
func (_u *OrganizationUpdateOne) ClearDefaultQuotaAmount() *OrganizationUpdateOne {
	_u.mutation.ClearDefaultQuotaAmount()
	return _u
}

// SetDefaultQuotaPeriodDays sets the "default_quota_period_days" field.
func (_u *OrganizationUpdateOne) SetDefaultQuotaPeriodDays(v int) *OrganizationUpdateOne {
	_u.mutation.ResetDefaultQuotaPeriodDays()
	_u.mutation.SetDefaultQuotaPeriodDays(v)
	return _u
}

// SetNillableDefaultQuotaPeriodDays sets the "default_quota_period_days" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableDefaultQuotaPeriodDays(v *int) *OrganizationUpdateOne {
	if v != nil {
		_u.SetDefaultQuotaPeriodDays(*v)
	}
	return _u
}

// AddDefaultQuotaPeriodDays adds value to the "default_quota_period_days" field.
func (_u *OrganizationUpdateOne) AddDefaultQuotaPeriodDays(v int) *OrganizationUpdateOne {
	_u.mutation.AddDefaultQuotaPeriodDays(v)
	return _u
}

// ClearDefaultQuotaPeriodDays clears the value of the "default_quota_period_days" field.
func (_u *OrganizationUpdateOne) ClearDefaultQuotaPeriodDays() *OrganizationUpdateOne {
	_u.mutation.ClearDefaultQuotaPeriodDays()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *OrganizationUpdateOne) SetOwnerID(id int64) *OrganizationUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *OrganizationUpdateOne) SetOwner(v *User) *OrganizationUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddMemberIDs adds the "members" edge to the OrganizationMember entity by IDs.
func (_u *OrganizationUpdateOne) AddMemberIDs(ids ...int64) *OrganizationUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the OrganizationMember entity.
func (_u *OrganizationUpdateOne) AddMembers(v ...*OrganizationMember) *OrganizationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddInvitationIDs adds the "invitations" edge to the RedeemCode entity by IDs.
func (_u *OrganizationUpdateOne) AddInvitationIDs(ids ...int64) *OrganizationUpdateOne {
	_u.mutation.AddInvitationIDs(ids...)
	return _u
}

// AddInvitations adds the "invitations" edges to the RedeemCode entity.
func (_u *OrganizationUpdateOne) AddInvitations(v ...*RedeemCode) *OrganizationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvitationIDs(ids...)
}

// AddAllowedGroupIDs adds the "allowed_groups" edge to the Group entity by IDs.
func (_u *OrganizationUpdateOne) AddAllowedGroupIDs(ids ...int64) *OrganizationUpdateOne {
	_u.mutation.AddAllowedGroupIDs(ids...)
	return _u
}

// AddAllowedGroups adds the "allowed_groups" edges to the Group entity.
func (_u *OrganizationUpdateOne) AddAllowedGroups(v ...*Group) *OrganizationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAllowedGroupIDs(ids...)
}

// Mutation returns the OrganizationMutation object of the builder.
func (_u *OrganizationUpdateOne) Mutation() *OrganizationMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *OrganizationUpdateOne) ClearOwner() *OrganizationUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMembers clears all "members" edges to the OrganizationMember entity.
func (_u *OrganizationUpdateOne) ClearMembers() *OrganizationUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to OrganizationMember entities by IDs.
func (_u *OrganizationUpdateOne) RemoveMemberIDs(ids ...int64) *OrganizationUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to OrganizationMember entities.
func (_u *OrganizationUpdateOne) RemoveMembers(v ...*OrganizationMember) *OrganizationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearInvitations clears all "invitations" edges to the RedeemCode entity.
func (_u *OrganizationUpdateOne) ClearInvitations() *OrganizationUpdateOne {
	_u.mutation.ClearInvitations()
	return _u
}

// RemoveInvitationIDs removes the "invitations" edge to RedeemCode entities by IDs.
func (_u *OrganizationUpdateOne) RemoveInvitationIDs(ids ...int64) *OrganizationUpdateOne {
	_u.mutation.RemoveInvitationIDs(ids...)
	return _u
}

// RemoveInvitations removes "invitations" edges to RedeemCode entities.
func (_u *OrganizationUpdateOne) RemoveInvitations(v ...*RedeemCode) *OrganizationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvitationIDs(ids...)
}

// ClearAllowedGroups clears all "allowed_groups" edges to the Group entity.
func (_u *OrganizationUpdateOne) ClearAllowedGroups() *OrganizationUpdateOne {
	_u.mutation.ClearAllowedGroups()
	return _u
}

// RemoveAllowedGroupIDs removes the "allowed_groups" edge to Group entities by IDs.
func (_u *OrganizationUpdateOne) RemoveAllowedGroupIDs(ids ...int64) *OrganizationUpdateOne {
	_u.mutation.RemoveAllowedGroupIDs(ids...)
	return _u
}

// RemoveAllowedGroups removes "allowed_groups" edges to Group entities.
func (_u *OrganizationUpdateOne) RemoveAllowedGroups(v ...*Group) *OrganizationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAllowedGroupIDs(ids...)
}

// Where appends a list predicates to the OrganizationUpdate builder.
func (_u *OrganizationUpdateOne) Where(ps ...predicate.Organization) *OrganizationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrganizationUpdateOne) Select(field string, fields ...string) *OrganizationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Organization entity.
func (_u *OrganizationUpdateOne) Save(ctx context.Context) (*Organization, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationUpdateOne) SaveX(ctx context.Context) *Organization {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrganizationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := organization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := organization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Organization.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := organization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Organization.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaRequestMode(); ok {
		if err := organization.QuotaRequestModeValidator(v); err != nil {
			return &ValidationError{Name: "quota_request_mode", err: fmt.Errorf(`ent: validator failed for field "Organization.quota_request_mode": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Organization.owner"`)
	}
	return nil
}

func (_u *OrganizationUpdateOne) sqlSave(ctx context.Context) (_node *Organization, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organization.Table, organization.Columns, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Organization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organization.FieldID)
		for _, f := range fields {
			if !organization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(organization.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RestrictPublicGroups(); ok {
		_spec.SetField(organization.FieldRestrictPublicGroups, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(organization.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaRequestMode(); ok {
		_spec.SetField(organization.FieldQuotaRequestMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaRequestMin(); ok {
		_spec.SetField(organization.FieldQuotaRequestMin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaRequestMin(); ok {
		_spec.AddField(organization.FieldQuotaRequestMin, field.TypeFloat64, value)
	}
	if _u.mutation.QuotaRequestMinCleared() {
		_spec.ClearField(organization.FieldQuotaRequestMin, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QuotaRequestMax(); ok {
		_spec.SetField(organization.FieldQuotaRequestMax, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaRequestMax(); ok {
		_spec.AddField(organization.FieldQuotaRequestMax, field.TypeFloat64, value)
	}
	if _u.mutation.QuotaRequestMaxCleared() {
		_spec.ClearField(organization.FieldQuotaRequestMax, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DefaultQuotaEnabled(); ok {
		_spec.SetField(organization.FieldDefaultQuotaEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultQuotaAmount(); ok {
		_spec.SetField(organization.FieldDefaultQuotaAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultQuotaAmount(); ok {
		_spec.AddField(organization.FieldDefaultQuotaAmount, field.TypeFloat64, value)
	}
	if _u.mutation.DefaultQuotaAmountCleared() {
		_spec.ClearField(organization.FieldDefaultQuotaAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DefaultQuotaPeriodDays(); ok {
		_spec.SetField(organization.FieldDefaultQuotaPeriodDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDefaultQuotaPeriodDays(); ok {
		_spec.AddField(organization.FieldDefaultQuotaPeriodDays, field.TypeInt, value)
	}
	if _u.mutation.DefaultQuotaPeriodDaysCleared() {
		_spec.ClearField(organization.FieldDefaultQuotaPeriodDays, field.TypeInt)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   organization.OwnerTable,
			Columns: []string{organization.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   organization.OwnerTable,
			Columns: []string{organization.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.InvitationsTable,
			Columns: []string{organization.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvitationsIDs(); len(nodes) > 0 && !_u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.InvitationsTable,
			Columns: []string{organization.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.InvitationsTable,
			Columns: []string{organization.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AllowedGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   organization.AllowedGroupsTable,
			Columns: organization.AllowedGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		createE := &OrganizationAllowedGroupCreate{config: _u.config, mutation: newOrganizationAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAllowedGroupsIDs(); len(nodes) > 0 && !_u.mutation.AllowedGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   organization.AllowedGroupsTable,
			Columns: organization.AllowedGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &OrganizationAllowedGroupCreate{config: _u.config, mutation: newOrganizationAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AllowedGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   organization.AllowedGroupsTable,
			Columns: organization.AllowedGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &OrganizationAllowedGroupCreate{config: _u.config, mutation: newOrganizationAllowedGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Organization{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
