// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/organizationquotarequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OrganizationQuotaRequestDelete is the builder for deleting a OrganizationQuotaRequest entity.
type OrganizationQuotaRequestDelete struct {
	config
	hooks    []Hook
	mutation *OrganizationQuotaRequestMutation
}

// Where appends a list predicates to the OrganizationQuotaRequestDelete builder.
func (_d *OrganizationQuotaRequestDelete) Where(ps ...predicate.OrganizationQuotaRequest) *OrganizationQuotaRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OrganizationQuotaRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrganizationQuotaRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OrganizationQuotaRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(organizationquotarequest.Table, sqlgraph.NewFieldSpec(organizationquotarequest.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OrganizationQuotaRequestDeleteOne is the builder for deleting a single OrganizationQuotaRequest entity.
type OrganizationQuotaRequestDeleteOne struct {
	_d *OrganizationQuotaRequestDelete
}

// Where appends a list predicates to the OrganizationQuotaRequestDelete builder.
func (_d *OrganizationQuotaRequestDeleteOne) Where(ps ...predicate.OrganizationQuotaRequest) *OrganizationQuotaRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OrganizationQuotaRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{organizationquotarequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrganizationQuotaRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
