// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/organizationallowedgroup"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OrganizationAllowedGroupDelete is the builder for deleting a OrganizationAllowedGroup entity.
type OrganizationAllowedGroupDelete struct {
	config
	hooks    []Hook
	mutation *OrganizationAllowedGroupMutation
}

// Where appends a list predicates to the OrganizationAllowedGroupDelete builder.
func (_d *OrganizationAllowedGroupDelete) Where(ps ...predicate.OrganizationAllowedGroup) *OrganizationAllowedGroupDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OrganizationAllowedGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrganizationAllowedGroupDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OrganizationAllowedGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(organizationallowedgroup.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OrganizationAllowedGroupDeleteOne is the builder for deleting a single OrganizationAllowedGroup entity.
type OrganizationAllowedGroupDeleteOne struct {
	_d *OrganizationAllowedGroupDelete
}

// Where appends a list predicates to the OrganizationAllowedGroupDelete builder.
func (_d *OrganizationAllowedGroupDeleteOne) Where(ps ...predicate.OrganizationAllowedGroup) *OrganizationAllowedGroupDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OrganizationAllowedGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{organizationallowedgroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrganizationAllowedGroupDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
