// Code generated by ent, DO NOT EDIT.

package organization

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldName, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldOwnerUserID, v))
}

// RestrictPublicGroups applies equality check predicate on the "restrict_public_groups" field. It's identical to RestrictPublicGroupsEQ.
func RestrictPublicGroups(v bool) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldRestrictPublicGroups, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldStatus, v))
}

// QuotaRequestMode applies equality check predicate on the "quota_request_mode" field. It's identical to QuotaRequestModeEQ.
func QuotaRequestMode(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldQuotaRequestMode, v))
}

// QuotaRequestMin applies equality check predicate on the "quota_request_min" field. It's identical to QuotaRequestMinEQ.
func QuotaRequestMin(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldQuotaRequestMin, v))
}

// QuotaRequestMax applies equality check predicate on the "quota_request_max" field. It's identical to QuotaRequestMaxEQ.
func QuotaRequestMax(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldQuotaRequestMax, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldName, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// RestrictPublicGroupsEQ applies the EQ predicate on the "restrict_public_groups" field.
func RestrictPublicGroupsEQ(v bool) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldRestrictPublicGroups, v))
}

// RestrictPublicGroupsNEQ applies the NEQ predicate on the "restrict_public_groups" field.
func RestrictPublicGroupsNEQ(v bool) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldRestrictPublicGroups, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldStatus, v))
}

// QuotaRequestModeEQ applies the EQ predicate on the "quota_request_mode" field.
func QuotaRequestModeEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldQuotaRequestMode, v))
}

// QuotaRequestModeNEQ applies the NEQ predicate on the "quota_request_mode" field.
func QuotaRequestModeNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldQuotaRequestMode, v))
}

// QuotaRequestModeIn applies the In predicate on the "quota_request_mode" field.
func QuotaRequestModeIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldQuotaRequestMode, vs...))
}

// QuotaRequestModeNotIn applies the NotIn predicate on the "quota_request_mode" field.
func QuotaRequestModeNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldQuotaRequestMode, vs...))
}

// QuotaRequestModeGT applies the GT predicate on the "quota_request_mode" field.
func QuotaRequestModeGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldQuotaRequestMode, v))
}

// QuotaRequestModeGTE applies the GTE predicate on the "quota_request_mode" field.
func QuotaRequestModeGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldQuotaRequestMode, v))
}

// QuotaRequestModeLT applies the LT predicate on the "quota_request_mode" field.
func QuotaRequestModeLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldQuotaRequestMode, v))
}

// QuotaRequestModeLTE applies the LTE predicate on the "quota_request_mode" field.
func QuotaRequestModeLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldQuotaRequestMode, v))
}

// QuotaRequestModeContains applies the Contains predicate on the "quota_request_mode" field.
func QuotaRequestModeContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldQuotaRequestMode, v))
}

// QuotaRequestModeHasPrefix applies the HasPrefix predicate on the "quota_request_mode" field.
func QuotaRequestModeHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldQuotaRequestMode, v))
}

// QuotaRequestModeHasSuffix applies the HasSuffix predicate on the "quota_request_mode" field.
func QuotaRequestModeHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldQuotaRequestMode, v))
}

// QuotaRequestModeEqualFold applies the EqualFold predicate on the "quota_request_mode" field.
func QuotaRequestModeEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldQuotaRequestMode, v))
}

// QuotaRequestModeContainsFold applies the ContainsFold predicate on the "quota_request_mode" field.
func QuotaRequestModeContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldQuotaRequestMode, v))
}

// QuotaRequestMinEQ applies the EQ predicate on the "quota_request_min" field.
func QuotaRequestMinEQ(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldQuotaRequestMin, v))
}

// QuotaRequestMinNEQ applies the NEQ predicate on the "quota_request_min" field.
func QuotaRequestMinNEQ(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldQuotaRequestMin, v))
}

// QuotaRequestMinIn applies the In predicate on the "quota_request_min" field.
func QuotaRequestMinIn(vs ...float64) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldQuotaRequestMin, vs...))
}

// QuotaRequestMinNotIn applies the NotIn predicate on the "quota_request_min" field.
func QuotaRequestMinNotIn(vs ...float64) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldQuotaRequestMin, vs...))
}

// QuotaRequestMinGT applies the GT predicate on the "quota_request_min" field.
func QuotaRequestMinGT(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldQuotaRequestMin, v))
}

// QuotaRequestMinGTE applies the GTE predicate on the "quota_request_min" field.
func QuotaRequestMinGTE(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldQuotaRequestMin, v))
}

// QuotaRequestMinLT applies the LT predicate on the "quota_request_min" field.
func QuotaRequestMinLT(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldQuotaRequestMin, v))
}

// QuotaRequestMinLTE applies the LTE predicate on the "quota_request_min" field.
func QuotaRequestMinLTE(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldQuotaRequestMin, v))
}

// QuotaRequestMinIsNil applies the IsNil predicate on the "quota_request_min" field.
func QuotaRequestMinIsNil() predicate.Organization {
	return predicate.Organization(sql.FieldIsNull(FieldQuotaRequestMin))
}

// QuotaRequestMinNotNil applies the NotNil predicate on the "quota_request_min" field.
func QuotaRequestMinNotNil() predicate.Organization {
	return predicate.Organization(sql.FieldNotNull(FieldQuotaRequestMin))
}

// QuotaRequestMaxEQ applies the EQ predicate on the "quota_request_max" field.
func QuotaRequestMaxEQ(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldQuotaRequestMax, v))
}

// QuotaRequestMaxNEQ applies the NEQ predicate on the "quota_request_max" field.
func QuotaRequestMaxNEQ(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldQuotaRequestMax, v))
}

// QuotaRequestMaxIn applies the In predicate on the "quota_request_max" field.
func QuotaRequestMaxIn(vs ...float64) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldQuotaRequestMax, vs...))
}

// QuotaRequestMaxNotIn applies the NotIn predicate on the "quota_request_max" field.
func QuotaRequestMaxNotIn(vs ...float64) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldQuotaRequestMax, vs...))
}

// QuotaRequestMaxGT applies the GT predicate on the "quota_request_max" field.
func QuotaRequestMaxGT(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldQuotaRequestMax, v))
}

// QuotaRequestMaxGTE applies the GTE predicate on the "quota_request_max" field.
func QuotaRequestMaxGTE(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldQuotaRequestMax, v))
}

// QuotaRequestMaxLT applies the LT predicate on the "quota_request_max" field.
func QuotaRequestMaxLT(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldQuotaRequestMax, v))
}

// QuotaRequestMaxLTE applies the LTE predicate on the "quota_request_max" field.
func QuotaRequestMaxLTE(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldQuotaRequestMax, v))
}

// QuotaRequestMaxIsNil applies the IsNil predicate on the "quota_request_max" field.
func QuotaRequestMaxIsNil() predicate.Organization {
	return predicate.Organization(sql.FieldIsNull(FieldQuotaRequestMax))
}

// QuotaRequestMaxNotNil applies the NotNil predicate on the "quota_request_max" field.
func QuotaRequestMaxNotNil() predicate.Organization {
	return predicate.Organization(sql.FieldNotNull(FieldQuotaRequestMax))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.OrganizationMember) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvitations applies the HasEdge predicate on the "invitations" edge.
func HasInvitations() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InvitationsTable, InvitationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvitationsWith applies the HasEdge predicate on the "invitations" edge with a given conditions (other predicates).
func HasInvitationsWith(preds ...predicate.RedeemCode) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newInvitationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAllowedGroups applies the HasEdge predicate on the "allowed_groups" edge.
func HasAllowedGroups() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, AllowedGroupsTable, AllowedGroupsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAllowedGroupsWith applies the HasEdge predicate on the "allowed_groups" edge with a given conditions (other predicates).
func HasAllowedGroupsWith(preds ...predicate.Group) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newAllowedGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrganizationAllowedGroups applies the HasEdge predicate on the "organization_allowed_groups" edge.
func HasOrganizationAllowedGroups() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, OrganizationAllowedGroupsTable, OrganizationAllowedGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationAllowedGroupsWith applies the HasEdge predicate on the "organization_allowed_groups" edge with a given conditions (other predicates).
func HasOrganizationAllowedGroupsWith(preds ...predicate.OrganizationAllowedGroup) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newOrganizationAllowedGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Organization) predicate.Organization {
	return predicate.Organization(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Organization) predicate.Organization {
	return predicate.Organization(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Organization) predicate.Organization {
	return predicate.Organization(sql.NotPredicates(p))
}
