// Code generated by ent, DO NOT EDIT.

package organizationquotarequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the organizationquotarequest type in the database.
	Label = "organization_quota_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldGrantSource holds the string denoting the grant_source field in the database.
	FieldGrantSource = "grant_source"
	// FieldGrantedAmount holds the string denoting the granted_amount field in the database.
	FieldGrantedAmount = "granted_amount"
	// FieldSnapshotMode holds the string denoting the snapshot_mode field in the database.
	FieldSnapshotMode = "snapshot_mode"
	// FieldSnapshotLimit holds the string denoting the snapshot_limit field in the database.
	FieldSnapshotLimit = "snapshot_limit"
	// FieldSnapshotUsed holds the string denoting the snapshot_used field in the database.
	FieldSnapshotUsed = "snapshot_used"
	// FieldReviewerUserID holds the string denoting the reviewer_user_id field in the database.
	FieldReviewerUserID = "reviewer_user_id"
	// FieldReviewedAt holds the string denoting the reviewed_at field in the database.
	FieldReviewedAt = "reviewed_at"
	// FieldReviewNote holds the string denoting the review_note field in the database.
	FieldReviewNote = "review_note"
	// Table holds the table name of the organizationquotarequest in the database.
	Table = "organization_quota_requests"
)

// Columns holds all SQL columns for organizationquotarequest fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOrganizationID,
	FieldUserID,
	FieldAmount,
	FieldReason,
	FieldStatus,
	FieldGrantSource,
	FieldGrantedAmount,
	FieldSnapshotMode,
	FieldSnapshotLimit,
	FieldSnapshotUsed,
	FieldReviewerUserID,
	FieldReviewedAt,
	FieldReviewNote,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// GrantSourceValidator is a validator for the "grant_source" field. It is called by the builders before save.
	GrantSourceValidator func(string) error
	// DefaultSnapshotMode holds the default value on creation for the "snapshot_mode" field.
	DefaultSnapshotMode string
	// SnapshotModeValidator is a validator for the "snapshot_mode" field. It is called by the builders before save.
	SnapshotModeValidator func(string) error
	// DefaultSnapshotUsed holds the default value on creation for the "snapshot_used" field.
	DefaultSnapshotUsed float64
	// ReviewNoteValidator is a validator for the "review_note" field. It is called by the builders before save.
	ReviewNoteValidator func(string) error
)

// OrderOption defines the ordering options for the OrganizationQuotaRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByGrantSource orders the results by the grant_source field.
func ByGrantSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantSource, opts...).ToFunc()
}

// ByGrantedAmount orders the results by the granted_amount field.
func ByGrantedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedAmount, opts...).ToFunc()
}

// BySnapshotMode orders the results by the snapshot_mode field.
func BySnapshotMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotMode, opts...).ToFunc()
}

// BySnapshotLimit orders the results by the snapshot_limit field.
func BySnapshotLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotLimit, opts...).ToFunc()
}

// BySnapshotUsed orders the results by the snapshot_used field.
func BySnapshotUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotUsed, opts...).ToFunc()
}

// ByReviewerUserID orders the results by the reviewer_user_id field.
func ByReviewerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewerUserID, opts...).ToFunc()
}

// ByReviewedAt orders the results by the reviewed_at field.
func ByReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedAt, opts...).ToFunc()
}

// ByReviewNote orders the results by the review_note field.
func ByReviewNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewNote, opts...).ToFunc()
}
