// Code generated by ent, DO NOT EDIT.

package organizationquotarequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldOrganizationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldAmount, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldReason, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldStatus, v))
}

// GrantSource applies equality check predicate on the "grant_source" field. It's identical to GrantSourceEQ.
func GrantSource(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldGrantSource, v))
}

// GrantedAmount applies equality check predicate on the "granted_amount" field. It's identical to GrantedAmountEQ.
func GrantedAmount(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldGrantedAmount, v))
}

// SnapshotMode applies equality check predicate on the "snapshot_mode" field. It's identical to SnapshotModeEQ.
func SnapshotMode(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldSnapshotMode, v))
}

// SnapshotLimit applies equality check predicate on the "snapshot_limit" field. It's identical to SnapshotLimitEQ.
func SnapshotLimit(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldSnapshotLimit, v))
}

// SnapshotUsed applies equality check predicate on the "snapshot_used" field. It's identical to SnapshotUsedEQ.
func SnapshotUsed(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldSnapshotUsed, v))
}

// ReviewerUserID applies equality check predicate on the "reviewer_user_id" field. It's identical to ReviewerUserIDEQ.
func ReviewerUserID(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldReviewerUserID, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewNote applies equality check predicate on the "review_note" field. It's identical to ReviewNoteEQ.
func ReviewNote(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldReviewNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDGT applies the GT predicate on the "organization_id" field.
func OrganizationIDGT(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldOrganizationID, v))
}

// OrganizationIDGTE applies the GTE predicate on the "organization_id" field.
func OrganizationIDGTE(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldOrganizationID, v))
}

// OrganizationIDLT applies the LT predicate on the "organization_id" field.
func OrganizationIDLT(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldOrganizationID, v))
}

// OrganizationIDLTE applies the LTE predicate on the "organization_id" field.
func OrganizationIDLTE(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldOrganizationID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldUserID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldAmount, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldContainsFold(FieldReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldContainsFold(FieldStatus, v))
}

// GrantSourceEQ applies the EQ predicate on the "grant_source" field.
func GrantSourceEQ(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldGrantSource, v))
}

// GrantSourceNEQ applies the NEQ predicate on the "grant_source" field.
func GrantSourceNEQ(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldGrantSource, v))
}

// GrantSourceIn applies the In predicate on the "grant_source" field.
func GrantSourceIn(vs ...string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldGrantSource, vs...))
}

// GrantSourceNotIn applies the NotIn predicate on the "grant_source" field.
func GrantSourceNotIn(vs ...string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldGrantSource, vs...))
}

// GrantSourceGT applies the GT predicate on the "grant_source" field.
func GrantSourceGT(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldGrantSource, v))
}

// GrantSourceGTE applies the GTE predicate on the "grant_source" field.
func GrantSourceGTE(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldGrantSource, v))
}

// GrantSourceLT applies the LT predicate on the "grant_source" field.
func GrantSourceLT(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldGrantSource, v))
}

// GrantSourceLTE applies the LTE predicate on the "grant_source" field.
func GrantSourceLTE(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldGrantSource, v))
}

// GrantSourceContains applies the Contains predicate on the "grant_source" field.
func GrantSourceContains(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldContains(FieldGrantSource, v))
}

// GrantSourceHasPrefix applies the HasPrefix predicate on the "grant_source" field.
func GrantSourceHasPrefix(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldHasPrefix(FieldGrantSource, v))
}

// GrantSourceHasSuffix applies the HasSuffix predicate on the "grant_source" field.
func GrantSourceHasSuffix(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldHasSuffix(FieldGrantSource, v))
}

// GrantSourceIsNil applies the IsNil predicate on the "grant_source" field.
func GrantSourceIsNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIsNull(FieldGrantSource))
}

// GrantSourceNotNil applies the NotNil predicate on the "grant_source" field.
func GrantSourceNotNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotNull(FieldGrantSource))
}

// GrantSourceEqualFold applies the EqualFold predicate on the "grant_source" field.
func GrantSourceEqualFold(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEqualFold(FieldGrantSource, v))
}

// GrantSourceContainsFold applies the ContainsFold predicate on the "grant_source" field.
func GrantSourceContainsFold(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldContainsFold(FieldGrantSource, v))
}

// GrantedAmountEQ applies the EQ predicate on the "granted_amount" field.
func GrantedAmountEQ(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldGrantedAmount, v))
}

// GrantedAmountNEQ applies the NEQ predicate on the "granted_amount" field.
func GrantedAmountNEQ(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldGrantedAmount, v))
}

// GrantedAmountIn applies the In predicate on the "granted_amount" field.
func GrantedAmountIn(vs ...float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldGrantedAmount, vs...))
}

// GrantedAmountNotIn applies the NotIn predicate on the "granted_amount" field.
func GrantedAmountNotIn(vs ...float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldGrantedAmount, vs...))
}

// GrantedAmountGT applies the GT predicate on the "granted_amount" field.
func GrantedAmountGT(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldGrantedAmount, v))
}

// GrantedAmountGTE applies the GTE predicate on the "granted_amount" field.
func GrantedAmountGTE(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldGrantedAmount, v))
}

// GrantedAmountLT applies the LT predicate on the "granted_amount" field.
func GrantedAmountLT(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldGrantedAmount, v))
}

// GrantedAmountLTE applies the LTE predicate on the "granted_amount" field.
func GrantedAmountLTE(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldGrantedAmount, v))
}

// GrantedAmountIsNil applies the IsNil predicate on the "granted_amount" field.
func GrantedAmountIsNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIsNull(FieldGrantedAmount))
}

// GrantedAmountNotNil applies the NotNil predicate on the "granted_amount" field.
func GrantedAmountNotNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotNull(FieldGrantedAmount))
}

// SnapshotModeEQ applies the EQ predicate on the "snapshot_mode" field.
func SnapshotModeEQ(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldSnapshotMode, v))
}

// SnapshotModeNEQ applies the NEQ predicate on the "snapshot_mode" field.
func SnapshotModeNEQ(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldSnapshotMode, v))
}

// SnapshotModeIn applies the In predicate on the "snapshot_mode" field.
func SnapshotModeIn(vs ...string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldSnapshotMode, vs...))
}

// SnapshotModeNotIn applies the NotIn predicate on the "snapshot_mode" field.
func SnapshotModeNotIn(vs ...string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldSnapshotMode, vs...))
}

// SnapshotModeGT applies the GT predicate on the "snapshot_mode" field.
func SnapshotModeGT(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldSnapshotMode, v))
}

// SnapshotModeGTE applies the GTE predicate on the "snapshot_mode" field.
func SnapshotModeGTE(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldSnapshotMode, v))
}

// SnapshotModeLT applies the LT predicate on the "snapshot_mode" field.
func SnapshotModeLT(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldSnapshotMode, v))
}

// SnapshotModeLTE applies the LTE predicate on the "snapshot_mode" field.
func SnapshotModeLTE(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldSnapshotMode, v))
}

// SnapshotModeContains applies the Contains predicate on the "snapshot_mode" field.
func SnapshotModeContains(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldContains(FieldSnapshotMode, v))
}

// SnapshotModeHasPrefix applies the HasPrefix predicate on the "snapshot_mode" field.
func SnapshotModeHasPrefix(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldHasPrefix(FieldSnapshotMode, v))
}

// SnapshotModeHasSuffix applies the HasSuffix predicate on the "snapshot_mode" field.
func SnapshotModeHasSuffix(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldHasSuffix(FieldSnapshotMode, v))
}

// SnapshotModeEqualFold applies the EqualFold predicate on the "snapshot_mode" field.
func SnapshotModeEqualFold(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEqualFold(FieldSnapshotMode, v))
}

// SnapshotModeContainsFold applies the ContainsFold predicate on the "snapshot_mode" field.
func SnapshotModeContainsFold(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldContainsFold(FieldSnapshotMode, v))
}

// SnapshotLimitEQ applies the EQ predicate on the "snapshot_limit" field.
func SnapshotLimitEQ(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldSnapshotLimit, v))
}

// SnapshotLimitNEQ applies the NEQ predicate on the "snapshot_limit" field.
func SnapshotLimitNEQ(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldSnapshotLimit, v))
}

// SnapshotLimitIn applies the In predicate on the "snapshot_limit" field.
func SnapshotLimitIn(vs ...float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldSnapshotLimit, vs...))
}

// SnapshotLimitNotIn applies the NotIn predicate on the "snapshot_limit" field.
func SnapshotLimitNotIn(vs ...float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldSnapshotLimit, vs...))
}

// SnapshotLimitGT applies the GT predicate on the "snapshot_limit" field.
func SnapshotLimitGT(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldSnapshotLimit, v))
}

// SnapshotLimitGTE applies the GTE predicate on the "snapshot_limit" field.
func SnapshotLimitGTE(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldSnapshotLimit, v))
}

// SnapshotLimitLT applies the LT predicate on the "snapshot_limit" field.
func SnapshotLimitLT(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldSnapshotLimit, v))
}

// SnapshotLimitLTE applies the LTE predicate on the "snapshot_limit" field.
func SnapshotLimitLTE(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldSnapshotLimit, v))
}

// SnapshotLimitIsNil applies the IsNil predicate on the "snapshot_limit" field.
func SnapshotLimitIsNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIsNull(FieldSnapshotLimit))
}

// SnapshotLimitNotNil applies the NotNil predicate on the "snapshot_limit" field.
func SnapshotLimitNotNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotNull(FieldSnapshotLimit))
}

// SnapshotUsedEQ applies the EQ predicate on the "snapshot_used" field.
func SnapshotUsedEQ(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldSnapshotUsed, v))
}

// SnapshotUsedNEQ applies the NEQ predicate on the "snapshot_used" field.
func SnapshotUsedNEQ(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldSnapshotUsed, v))
}

// SnapshotUsedIn applies the In predicate on the "snapshot_used" field.
func SnapshotUsedIn(vs ...float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldSnapshotUsed, vs...))
}

// SnapshotUsedNotIn applies the NotIn predicate on the "snapshot_used" field.
func SnapshotUsedNotIn(vs ...float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldSnapshotUsed, vs...))
}

// SnapshotUsedGT applies the GT predicate on the "snapshot_used" field.
func SnapshotUsedGT(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldSnapshotUsed, v))
}

// SnapshotUsedGTE applies the GTE predicate on the "snapshot_used" field.
func SnapshotUsedGTE(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldSnapshotUsed, v))
}

// SnapshotUsedLT applies the LT predicate on the "snapshot_used" field.
func SnapshotUsedLT(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldSnapshotUsed, v))
}

// SnapshotUsedLTE applies the LTE predicate on the "snapshot_used" field.
func SnapshotUsedLTE(v float64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldSnapshotUsed, v))
}

// ReviewerUserIDEQ applies the EQ predicate on the "reviewer_user_id" field.
func ReviewerUserIDEQ(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldReviewerUserID, v))
}

// ReviewerUserIDNEQ applies the NEQ predicate on the "reviewer_user_id" field.
func ReviewerUserIDNEQ(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldReviewerUserID, v))
}

// ReviewerUserIDIn applies the In predicate on the "reviewer_user_id" field.
func ReviewerUserIDIn(vs ...int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldReviewerUserID, vs...))
}

// ReviewerUserIDNotIn applies the NotIn predicate on the "reviewer_user_id" field.
func ReviewerUserIDNotIn(vs ...int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldReviewerUserID, vs...))
}

// ReviewerUserIDGT applies the GT predicate on the "reviewer_user_id" field.
func ReviewerUserIDGT(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldReviewerUserID, v))
}

// ReviewerUserIDGTE applies the GTE predicate on the "reviewer_user_id" field.
func ReviewerUserIDGTE(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldReviewerUserID, v))
}

// ReviewerUserIDLT applies the LT predicate on the "reviewer_user_id" field.
func ReviewerUserIDLT(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldReviewerUserID, v))
}

// ReviewerUserIDLTE applies the LTE predicate on the "reviewer_user_id" field.
func ReviewerUserIDLTE(v int64) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldReviewerUserID, v))
}

// ReviewerUserIDIsNil applies the IsNil predicate on the "reviewer_user_id" field.
func ReviewerUserIDIsNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIsNull(FieldReviewerUserID))
}

// ReviewerUserIDNotNil applies the NotNil predicate on the "reviewer_user_id" field.
func ReviewerUserIDNotNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotNull(FieldReviewerUserID))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotNull(FieldReviewedAt))
}

// ReviewNoteEQ applies the EQ predicate on the "review_note" field.
func ReviewNoteEQ(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEQ(FieldReviewNote, v))
}

// ReviewNoteNEQ applies the NEQ predicate on the "review_note" field.
func ReviewNoteNEQ(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNEQ(FieldReviewNote, v))
}

// ReviewNoteIn applies the In predicate on the "review_note" field.
func ReviewNoteIn(vs ...string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIn(FieldReviewNote, vs...))
}

// ReviewNoteNotIn applies the NotIn predicate on the "review_note" field.
func ReviewNoteNotIn(vs ...string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotIn(FieldReviewNote, vs...))
}

// ReviewNoteGT applies the GT predicate on the "review_note" field.
func ReviewNoteGT(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGT(FieldReviewNote, v))
}

// ReviewNoteGTE applies the GTE predicate on the "review_note" field.
func ReviewNoteGTE(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldGTE(FieldReviewNote, v))
}

// ReviewNoteLT applies the LT predicate on the "review_note" field.
func ReviewNoteLT(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLT(FieldReviewNote, v))
}

// ReviewNoteLTE applies the LTE predicate on the "review_note" field.
func ReviewNoteLTE(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldLTE(FieldReviewNote, v))
}

// ReviewNoteContains applies the Contains predicate on the "review_note" field.
func ReviewNoteContains(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldContains(FieldReviewNote, v))
}

// ReviewNoteHasPrefix applies the HasPrefix predicate on the "review_note" field.
func ReviewNoteHasPrefix(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldHasPrefix(FieldReviewNote, v))
}

// ReviewNoteHasSuffix applies the HasSuffix predicate on the "review_note" field.
func ReviewNoteHasSuffix(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldHasSuffix(FieldReviewNote, v))
}

// ReviewNoteIsNil applies the IsNil predicate on the "review_note" field.
func ReviewNoteIsNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldIsNull(FieldReviewNote))
}

// ReviewNoteNotNil applies the NotNil predicate on the "review_note" field.
func ReviewNoteNotNil() predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldNotNull(FieldReviewNote))
}

// ReviewNoteEqualFold applies the EqualFold predicate on the "review_note" field.
func ReviewNoteEqualFold(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldEqualFold(FieldReviewNote, v))
}

// ReviewNoteContainsFold applies the ContainsFold predicate on the "review_note" field.
func ReviewNoteContainsFold(v string) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.FieldContainsFold(FieldReviewNote, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrganizationQuotaRequest) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrganizationQuotaRequest) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrganizationQuotaRequest) predicate.OrganizationQuotaRequest {
	return predicate.OrganizationQuotaRequest(sql.NotPredicates(p))
}
