// Code generated by ent, DO NOT EDIT.

package organizationmember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldOrganizationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldUserID, v))
}

// SpendingLimit applies equality check predicate on the "spending_limit" field. It's identical to SpendingLimitEQ.
func SpendingLimit(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldSpendingLimit, v))
}

// SpendingUsed applies equality check predicate on the "spending_used" field. It's identical to SpendingUsedEQ.
func SpendingUsed(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldSpendingUsed, v))
}

// SpendingFrozen applies equality check predicate on the "spending_frozen" field. It's identical to SpendingFrozenEQ.
func SpendingFrozen(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldSpendingFrozen, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNotIn(FieldUserID, vs...))
}

// SpendingLimitEQ applies the EQ predicate on the "spending_limit" field.
func SpendingLimitEQ(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldSpendingLimit, v))
}

// SpendingLimitNEQ applies the NEQ predicate on the "spending_limit" field.
func SpendingLimitNEQ(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNEQ(FieldSpendingLimit, v))
}

// SpendingLimitIn applies the In predicate on the "spending_limit" field.
func SpendingLimitIn(vs ...float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldIn(FieldSpendingLimit, vs...))
}

// SpendingLimitNotIn applies the NotIn predicate on the "spending_limit" field.
func SpendingLimitNotIn(vs ...float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNotIn(FieldSpendingLimit, vs...))
}

// SpendingLimitGT applies the GT predicate on the "spending_limit" field.
func SpendingLimitGT(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGT(FieldSpendingLimit, v))
}

// SpendingLimitGTE applies the GTE predicate on the "spending_limit" field.
func SpendingLimitGTE(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGTE(FieldSpendingLimit, v))
}

// SpendingLimitLT applies the LT predicate on the "spending_limit" field.
func SpendingLimitLT(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLT(FieldSpendingLimit, v))
}

// SpendingLimitLTE applies the LTE predicate on the "spending_limit" field.
func SpendingLimitLTE(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLTE(FieldSpendingLimit, v))
}

// SpendingLimitIsNil applies the IsNil predicate on the "spending_limit" field.
func SpendingLimitIsNil() predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldIsNull(FieldSpendingLimit))
}

// SpendingLimitNotNil applies the NotNil predicate on the "spending_limit" field.
func SpendingLimitNotNil() predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNotNull(FieldSpendingLimit))
}

// SpendingUsedEQ applies the EQ predicate on the "spending_used" field.
func SpendingUsedEQ(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldSpendingUsed, v))
}

// SpendingUsedNEQ applies the NEQ predicate on the "spending_used" field.
func SpendingUsedNEQ(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNEQ(FieldSpendingUsed, v))
}

// SpendingUsedIn applies the In predicate on the "spending_used" field.
func SpendingUsedIn(vs ...float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldIn(FieldSpendingUsed, vs...))
}

// SpendingUsedNotIn applies the NotIn predicate on the "spending_used" field.
func SpendingUsedNotIn(vs ...float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNotIn(FieldSpendingUsed, vs...))
}

// SpendingUsedGT applies the GT predicate on the "spending_used" field.
func SpendingUsedGT(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGT(FieldSpendingUsed, v))
}

// SpendingUsedGTE applies the GTE predicate on the "spending_used" field.
func SpendingUsedGTE(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGTE(FieldSpendingUsed, v))
}

// SpendingUsedLT applies the LT predicate on the "spending_used" field.
func SpendingUsedLT(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLT(FieldSpendingUsed, v))
}

// SpendingUsedLTE applies the LTE predicate on the "spending_used" field.
func SpendingUsedLTE(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLTE(FieldSpendingUsed, v))
}

// SpendingFrozenEQ applies the EQ predicate on the "spending_frozen" field.
func SpendingFrozenEQ(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldEQ(FieldSpendingFrozen, v))
}

// SpendingFrozenNEQ applies the NEQ predicate on the "spending_frozen" field.
func SpendingFrozenNEQ(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNEQ(FieldSpendingFrozen, v))
}

// SpendingFrozenIn applies the In predicate on the "spending_frozen" field.
func SpendingFrozenIn(vs ...float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldIn(FieldSpendingFrozen, vs...))
}

// SpendingFrozenNotIn applies the NotIn predicate on the "spending_frozen" field.
func SpendingFrozenNotIn(vs ...float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldNotIn(FieldSpendingFrozen, vs...))
}

// SpendingFrozenGT applies the GT predicate on the "spending_frozen" field.
func SpendingFrozenGT(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGT(FieldSpendingFrozen, v))
}

// SpendingFrozenGTE applies the GTE predicate on the "spending_frozen" field.
func SpendingFrozenGTE(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldGTE(FieldSpendingFrozen, v))
}

// SpendingFrozenLT applies the LT predicate on the "spending_frozen" field.
func SpendingFrozenLT(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLT(FieldSpendingFrozen, v))
}

// SpendingFrozenLTE applies the LTE predicate on the "spending_frozen" field.
func SpendingFrozenLTE(v float64) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.FieldLTE(FieldSpendingFrozen, v))
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.OrganizationMember {
	return predicate.OrganizationMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.OrganizationMember {
	return predicate.OrganizationMember(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OrganizationMember {
	return predicate.OrganizationMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OrganizationMember {
	return predicate.OrganizationMember(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrganizationMember) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrganizationMember) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrganizationMember) predicate.OrganizationMember {
	return predicate.OrganizationMember(sql.NotPredicates(p))
}
