import type { BackendError } from '@/lib/server/sub2api/envelope';
import type { AuthErrorReason } from '@/lib/session/types';

/**
 * 后端错误 → 官网对浏览器暴露的错误原因。纯函数，单测锁住。
 * 浏览器只拿到归好类的原因，按原因显示中文提示；后端的英文说明只进服务端日志。
 */
const BY_BACKEND_REASON: Record<string, AuthErrorReason> = {
  // 登录
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
  ORGANIZATION_DISABLED: 'ORGANIZATION_DISABLED',
  TOTP_INVALID_CODE: 'TOTP_INVALID_CODE',
  TOTP_TOO_MANY_ATTEMPTS: 'TOO_MANY_REQUESTS',
  // 注册（同名照搬）
  REGISTRATION_DISABLED: 'REGISTRATION_DISABLED',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  EMAIL_RESERVED: 'EMAIL_RESERVED',
  EMAIL_SUFFIX_NOT_ALLOWED: 'EMAIL_SUFFIX_NOT_ALLOWED',
  EMAIL_DOMAIN_REGISTRATION_LIMIT: 'EMAIL_DOMAIN_REGISTRATION_LIMIT',
  EMAIL_VERIFY_REQUIRED: 'EMAIL_VERIFY_REQUIRED',
  VERIFY_CODE_REQUIRED: 'VERIFY_CODE_REQUIRED',
  INVALID_VERIFY_CODE: 'INVALID_VERIFY_CODE',
  VERIFY_CODE_TOO_FREQUENT: 'VERIFY_CODE_TOO_FREQUENT',
  VERIFY_CODE_MAX_ATTEMPTS: 'VERIFY_CODE_MAX_ATTEMPTS',
  INVITATION_CODE_REQUIRED: 'INVITATION_CODE_REQUIRED',
  INVITATION_CODE_INVALID: 'INVITATION_CODE_INVALID',
  ORGANIZATION_NAME_INVALID: 'ORGANIZATION_NAME_INVALID',
  ORGANIZATION_MEMBER_NAME_INVALID: 'ORGANIZATION_MEMBER_NAME_INVALID',
  ORGANIZATION_REGISTRATION_CONFLICT: 'ORGANIZATION_REGISTRATION_CONFLICT',
  USER_ALREADY_IN_ORGANIZATION: 'USER_ALREADY_IN_ORGANIZATION',
  // 优惠码的各种失败在提交时统一按「优惠码无效」提示（输入时的实时校验另有细分）
  PROMO_CODE_NOT_FOUND: 'PROMO_CODE_INVALID',
  PROMO_CODE_EXPIRED: 'PROMO_CODE_INVALID',
  PROMO_CODE_DISABLED: 'PROMO_CODE_INVALID',
  PROMO_CODE_MAX_USED: 'PROMO_CODE_INVALID',
  PROMO_CODE_ALREADY_USED: 'PROMO_CODE_INVALID',
  PROMO_CODE_INVALID: 'PROMO_CODE_INVALID',
  // 谷歌登录完成注册：待完成会话找不到、过期、已用过或不是这个浏览器发起的，都要重新用谷歌登录
  PENDING_AUTH_SESSION_NOT_FOUND: 'OAUTH_SESSION_EXPIRED',
  PENDING_AUTH_SESSION_EXPIRED: 'OAUTH_SESSION_EXPIRED',
  PENDING_AUTH_SESSION_CONSUMED: 'OAUTH_SESSION_EXPIRED',
  PENDING_AUTH_SESSION_INVALID: 'OAUTH_SESSION_EXPIRED',
  PENDING_AUTH_BROWSER_MISMATCH: 'OAUTH_SESSION_EXPIRED',
  // 谷歌邮箱已被别的账号占用
  AUTH_IDENTITY_OWNERSHIP_CONFLICT: 'EMAIL_EXISTS',
  // 找回密码：后台没开、重置链接无效或已过期（链接只能用一次，30 分钟内有效）
  PASSWORD_RESET_DISABLED: 'PASSWORD_RESET_DISABLED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  // 人机验证：Cloudflare 的验证没通过（没带、过期或用过）可以重新验证；
  // 后台验证配置有问题、开的是官网不支持的腾讯或阿里验证码时，客户自己解决不了
  TURNSTILE_VERIFICATION_FAILED: 'CAPTCHA_FAILED',
  TURNSTILE_NOT_CONFIGURED: 'CAPTCHA_UNAVAILABLE',
  TURNSTILE_INVALID_SECRET_KEY: 'CAPTCHA_UNAVAILABLE',
  TENCENT_CAPTCHA_VERIFICATION_FAILED: 'CAPTCHA_UNAVAILABLE',
  TENCENT_CAPTCHA_NOT_CONFIGURED: 'CAPTCHA_UNAVAILABLE',
  ALIYUN_CAPTCHA_VERIFICATION_FAILED: 'CAPTCHA_UNAVAILABLE',
  ALIYUN_CAPTCHA_NOT_CONFIGURED: 'CAPTCHA_UNAVAILABLE',
  CAPTCHA_INVALID_CREDENTIALS: 'CAPTCHA_UNAVAILABLE',
  CAPTCHA_PROVIDER_CONFLICT: 'CAPTCHA_UNAVAILABLE',
};

export function authReasonFor(error: BackendError): AuthErrorReason {
  const mapped = BY_BACKEND_REASON[error.reason];
  if (mapped) return mapped;
  if (error.status === 429) return 'TOO_MANY_REQUESTS';
  if (error.status >= 500) return 'BACKEND_UNAVAILABLE';
  if (error.status === 401) return 'NOT_LOGGED_IN';
  if (error.status === 400) return 'BAD_REQUEST';
  return 'UNKNOWN';
}

/** 浏览器看到的状态码：后端 5xx 一律按 503 给，其余照搬 */
export function browserStatusFor(error: BackendError): number {
  return error.status >= 500 ? 503 : error.status;
}
