import type { BackendError } from '@/lib/server/sub2api/envelope';
import type { AuthErrorReason } from '@/lib/session/types';

/**
 * 后端错误 → 官网对浏览器暴露的错误原因。纯函数，单测锁住。
 * 浏览器只拿到归好类的原因，按原因显示中文提示；后端的英文说明只进服务端日志。
 */
const BY_BACKEND_REASON: Record<string, AuthErrorReason> = {
  // 登录
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
  ORGANIZATION_DISABLED: 'ORGANIZATION_DISABLED',
  TOTP_INVALID_CODE: 'TOTP_INVALID_CODE',
  TOTP_TOO_MANY_ATTEMPTS: 'TOO_MANY_REQUESTS',
  // 注册（同名照搬）
  REGISTRATION_DISABLED: 'REGISTRATION_DISABLED',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  EMAIL_RESERVED: 'EMAIL_RESERVED',
  EMAIL_SUFFIX_NOT_ALLOWED: 'EMAIL_SUFFIX_NOT_ALLOWED',
  EMAIL_DOMAIN_REGISTRATION_LIMIT: 'EMAIL_DOMAIN_REGISTRATION_LIMIT',
  EMAIL_VERIFY_REQUIRED: 'EMAIL_VERIFY_REQUIRED',
  VERIFY_CODE_REQUIRED: 'VERIFY_CODE_REQUIRED',
  INVALID_VERIFY_CODE: 'INVALID_VERIFY_CODE',
  VERIFY_CODE_TOO_FREQUENT: 'VERIFY_CODE_TOO_FREQUENT',
  VERIFY_CODE_MAX_ATTEMPTS: 'VERIFY_CODE_MAX_ATTEMPTS',
  INVITATION_CODE_REQUIRED: 'INVITATION_CODE_REQUIRED',
  INVITATION_CODE_INVALID: 'INVITATION_CODE_INVALID',
  ORGANIZATION_NAME_INVALID: 'ORGANIZATION_NAME_INVALID',
  ORGANIZATION_MEMBER_NAME_INVALID: 'ORGANIZATION_MEMBER_NAME_INVALID',
  ORGANIZATION_REGISTRATION_CONFLICT: 'ORGANIZATION_REGISTRATION_CONFLICT',
  USER_ALREADY_IN_ORGANIZATION: 'USER_ALREADY_IN_ORGANIZATION',
  // 优惠码的各种失败在提交时统一按「优惠码无效」提示（输入时的实时校验另有细分）
  PROMO_CODE_NOT_FOUND: 'PROMO_CODE_INVALID',
  PROMO_CODE_EXPIRED: 'PROMO_CODE_INVALID',
  PROMO_CODE_DISABLED: 'PROMO_CODE_INVALID',
  PROMO_CODE_MAX_USED: 'PROMO_CODE_INVALID',
  PROMO_CODE_ALREADY_USED: 'PROMO_CODE_INVALID',
  PROMO_CODE_INVALID: 'PROMO_CODE_INVALID',
  // 后台开了人机验证（官网暂不支持），各家验证码的错误都归到这一类
  TURNSTILE_VERIFICATION_FAILED: 'CAPTCHA_REQUIRED',
  TURNSTILE_NOT_CONFIGURED: 'CAPTCHA_REQUIRED',
  TURNSTILE_INVALID_SECRET_KEY: 'CAPTCHA_REQUIRED',
  TENCENT_CAPTCHA_VERIFICATION_FAILED: 'CAPTCHA_REQUIRED',
  TENCENT_CAPTCHA_NOT_CONFIGURED: 'CAPTCHA_REQUIRED',
  ALIYUN_CAPTCHA_VERIFICATION_FAILED: 'CAPTCHA_REQUIRED',
  ALIYUN_CAPTCHA_NOT_CONFIGURED: 'CAPTCHA_REQUIRED',
  CAPTCHA_INVALID_CREDENTIALS: 'CAPTCHA_REQUIRED',
  CAPTCHA_PROVIDER_CONFLICT: 'CAPTCHA_REQUIRED',
};

export function authReasonFor(error: BackendError): AuthErrorReason {
  const mapped = BY_BACKEND_REASON[error.reason];
  if (mapped) return mapped;
  if (error.status === 429) return 'TOO_MANY_REQUESTS';
  if (error.status >= 500) return 'BACKEND_UNAVAILABLE';
  if (error.status === 401) return 'NOT_LOGGED_IN';
  if (error.status === 400) return 'BAD_REQUEST';
  return 'UNKNOWN';
}

/** 浏览器看到的状态码：后端 5xx 一律按 503 给，其余照搬 */
export function browserStatusFor(error: BackendError): number {
  return error.status >= 500 ? 503 : error.status;
}
